package com.sy.modules.dao.oa;

import com.sy.modules.common.MyBatisRepository;
import com.sy.modules.entity.oa.OaCustomer;
import com.sy.modules.entity.oa.OaCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
@MyBatisRepository
public interface OaCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    int countByExample(OaCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    int deleteByExample(OaCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    int insert(OaCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    int insertSelective(OaCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    List<OaCustomer> selectByExampleWithRowbounds(OaCustomerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    List<OaCustomer> selectByExample(OaCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    OaCustomer selectByPrimaryKey(Long cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OaCustomer record, @Param("example") OaCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OaCustomer record, @Param("example") OaCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OaCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OaCustomer record);
}