package com.sy.modules.dao.oa;

import com.sy.modules.common.MyBatisRepository;
import com.sy.modules.entity.oa.OaLinkman;
import com.sy.modules.entity.oa.OaLinkmanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
@MyBatisRepository
public interface OaLinkmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    int countByExample(OaLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    int deleteByExample(OaLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long lmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    int insert(OaLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    int insertSelective(OaLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    List<OaLinkman> selectByExampleWithRowbounds(OaLinkmanExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    List<OaLinkman> selectByExample(OaLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    OaLinkman selectByPrimaryKey(Long lmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OaLinkman record, @Param("example") OaLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OaLinkman record, @Param("example") OaLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OaLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OaLinkman record);
}