package com.sy.modules.entity.oa;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OaCustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    public OaCustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCIdIsNull() {
            addCriterion("c_id is null");
            return (Criteria) this;
        }

        public Criteria andCIdIsNotNull() {
            addCriterion("c_id is not null");
            return (Criteria) this;
        }

        public Criteria andCIdEqualTo(Long value) {
            addCriterion("c_id =", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotEqualTo(Long value) {
            addCriterion("c_id <>", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThan(Long value) {
            addCriterion("c_id >", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThanOrEqualTo(Long value) {
            addCriterion("c_id >=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThan(Long value) {
            addCriterion("c_id <", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThanOrEqualTo(Long value) {
            addCriterion("c_id <=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdIn(List<Long> values) {
            addCriterion("c_id in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotIn(List<Long> values) {
            addCriterion("c_id not in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdBetween(Long value1, Long value2) {
            addCriterion("c_id between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotBetween(Long value1, Long value2) {
            addCriterion("c_id not between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andCNameIsNull() {
            addCriterion("c_name is null");
            return (Criteria) this;
        }

        public Criteria andCNameIsNotNull() {
            addCriterion("c_name is not null");
            return (Criteria) this;
        }

        public Criteria andCNameEqualTo(String value) {
            addCriterion("c_name =", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotEqualTo(String value) {
            addCriterion("c_name <>", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThan(String value) {
            addCriterion("c_name >", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThanOrEqualTo(String value) {
            addCriterion("c_name >=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThan(String value) {
            addCriterion("c_name <", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThanOrEqualTo(String value) {
            addCriterion("c_name <=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLike(String value) {
            addCriterion("c_name like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotLike(String value) {
            addCriterion("c_name not like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameIn(List<String> values) {
            addCriterion("c_name in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotIn(List<String> values) {
            addCriterion("c_name not in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameBetween(String value1, String value2) {
            addCriterion("c_name between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotBetween(String value1, String value2) {
            addCriterion("c_name not between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andSysUserIdIsNull() {
            addCriterion("sys_user_id is null");
            return (Criteria) this;
        }

        public Criteria andSysUserIdIsNotNull() {
            addCriterion("sys_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andSysUserIdEqualTo(Long value) {
            addCriterion("sys_user_id =", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotEqualTo(Long value) {
            addCriterion("sys_user_id <>", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdGreaterThan(Long value) {
            addCriterion("sys_user_id >", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sys_user_id >=", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdLessThan(Long value) {
            addCriterion("sys_user_id <", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdLessThanOrEqualTo(Long value) {
            addCriterion("sys_user_id <=", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdIn(List<Long> values) {
            addCriterion("sys_user_id in", values, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotIn(List<Long> values) {
            addCriterion("sys_user_id not in", values, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdBetween(Long value1, Long value2) {
            addCriterion("sys_user_id between", value1, value2, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotBetween(Long value1, Long value2) {
            addCriterion("sys_user_id not between", value1, value2, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andCMobileIsNull() {
            addCriterion("c_mobile is null");
            return (Criteria) this;
        }

        public Criteria andCMobileIsNotNull() {
            addCriterion("c_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andCMobileEqualTo(String value) {
            addCriterion("c_mobile =", value, "cMobile");
            return (Criteria) this;
        }

        public Criteria andCMobileNotEqualTo(String value) {
            addCriterion("c_mobile <>", value, "cMobile");
            return (Criteria) this;
        }

        public Criteria andCMobileGreaterThan(String value) {
            addCriterion("c_mobile >", value, "cMobile");
            return (Criteria) this;
        }

        public Criteria andCMobileGreaterThanOrEqualTo(String value) {
            addCriterion("c_mobile >=", value, "cMobile");
            return (Criteria) this;
        }

        public Criteria andCMobileLessThan(String value) {
            addCriterion("c_mobile <", value, "cMobile");
            return (Criteria) this;
        }

        public Criteria andCMobileLessThanOrEqualTo(String value) {
            addCriterion("c_mobile <=", value, "cMobile");
            return (Criteria) this;
        }

        public Criteria andCMobileLike(String value) {
            addCriterion("c_mobile like", value, "cMobile");
            return (Criteria) this;
        }

        public Criteria andCMobileNotLike(String value) {
            addCriterion("c_mobile not like", value, "cMobile");
            return (Criteria) this;
        }

        public Criteria andCMobileIn(List<String> values) {
            addCriterion("c_mobile in", values, "cMobile");
            return (Criteria) this;
        }

        public Criteria andCMobileNotIn(List<String> values) {
            addCriterion("c_mobile not in", values, "cMobile");
            return (Criteria) this;
        }

        public Criteria andCMobileBetween(String value1, String value2) {
            addCriterion("c_mobile between", value1, value2, "cMobile");
            return (Criteria) this;
        }

        public Criteria andCMobileNotBetween(String value1, String value2) {
            addCriterion("c_mobile not between", value1, value2, "cMobile");
            return (Criteria) this;
        }

        public Criteria andCPhoneIsNull() {
            addCriterion("c_phone is null");
            return (Criteria) this;
        }

        public Criteria andCPhoneIsNotNull() {
            addCriterion("c_phone is not null");
            return (Criteria) this;
        }

        public Criteria andCPhoneEqualTo(String value) {
            addCriterion("c_phone =", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneNotEqualTo(String value) {
            addCriterion("c_phone <>", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneGreaterThan(String value) {
            addCriterion("c_phone >", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("c_phone >=", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneLessThan(String value) {
            addCriterion("c_phone <", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneLessThanOrEqualTo(String value) {
            addCriterion("c_phone <=", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneLike(String value) {
            addCriterion("c_phone like", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneNotLike(String value) {
            addCriterion("c_phone not like", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneIn(List<String> values) {
            addCriterion("c_phone in", values, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneNotIn(List<String> values) {
            addCriterion("c_phone not in", values, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneBetween(String value1, String value2) {
            addCriterion("c_phone between", value1, value2, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneNotBetween(String value1, String value2) {
            addCriterion("c_phone not between", value1, value2, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCAreaIsNull() {
            addCriterion("c_area is null");
            return (Criteria) this;
        }

        public Criteria andCAreaIsNotNull() {
            addCriterion("c_area is not null");
            return (Criteria) this;
        }

        public Criteria andCAreaEqualTo(String value) {
            addCriterion("c_area =", value, "cArea");
            return (Criteria) this;
        }

        public Criteria andCAreaNotEqualTo(String value) {
            addCriterion("c_area <>", value, "cArea");
            return (Criteria) this;
        }

        public Criteria andCAreaGreaterThan(String value) {
            addCriterion("c_area >", value, "cArea");
            return (Criteria) this;
        }

        public Criteria andCAreaGreaterThanOrEqualTo(String value) {
            addCriterion("c_area >=", value, "cArea");
            return (Criteria) this;
        }

        public Criteria andCAreaLessThan(String value) {
            addCriterion("c_area <", value, "cArea");
            return (Criteria) this;
        }

        public Criteria andCAreaLessThanOrEqualTo(String value) {
            addCriterion("c_area <=", value, "cArea");
            return (Criteria) this;
        }

        public Criteria andCAreaLike(String value) {
            addCriterion("c_area like", value, "cArea");
            return (Criteria) this;
        }

        public Criteria andCAreaNotLike(String value) {
            addCriterion("c_area not like", value, "cArea");
            return (Criteria) this;
        }

        public Criteria andCAreaIn(List<String> values) {
            addCriterion("c_area in", values, "cArea");
            return (Criteria) this;
        }

        public Criteria andCAreaNotIn(List<String> values) {
            addCriterion("c_area not in", values, "cArea");
            return (Criteria) this;
        }

        public Criteria andCAreaBetween(String value1, String value2) {
            addCriterion("c_area between", value1, value2, "cArea");
            return (Criteria) this;
        }

        public Criteria andCAreaNotBetween(String value1, String value2) {
            addCriterion("c_area not between", value1, value2, "cArea");
            return (Criteria) this;
        }

        public Criteria andCLinkmanIsNull() {
            addCriterion("c_linkman is null");
            return (Criteria) this;
        }

        public Criteria andCLinkmanIsNotNull() {
            addCriterion("c_linkman is not null");
            return (Criteria) this;
        }

        public Criteria andCLinkmanEqualTo(String value) {
            addCriterion("c_linkman =", value, "cLinkman");
            return (Criteria) this;
        }

        public Criteria andCLinkmanNotEqualTo(String value) {
            addCriterion("c_linkman <>", value, "cLinkman");
            return (Criteria) this;
        }

        public Criteria andCLinkmanGreaterThan(String value) {
            addCriterion("c_linkman >", value, "cLinkman");
            return (Criteria) this;
        }

        public Criteria andCLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("c_linkman >=", value, "cLinkman");
            return (Criteria) this;
        }

        public Criteria andCLinkmanLessThan(String value) {
            addCriterion("c_linkman <", value, "cLinkman");
            return (Criteria) this;
        }

        public Criteria andCLinkmanLessThanOrEqualTo(String value) {
            addCriterion("c_linkman <=", value, "cLinkman");
            return (Criteria) this;
        }

        public Criteria andCLinkmanLike(String value) {
            addCriterion("c_linkman like", value, "cLinkman");
            return (Criteria) this;
        }

        public Criteria andCLinkmanNotLike(String value) {
            addCriterion("c_linkman not like", value, "cLinkman");
            return (Criteria) this;
        }

        public Criteria andCLinkmanIn(List<String> values) {
            addCriterion("c_linkman in", values, "cLinkman");
            return (Criteria) this;
        }

        public Criteria andCLinkmanNotIn(List<String> values) {
            addCriterion("c_linkman not in", values, "cLinkman");
            return (Criteria) this;
        }

        public Criteria andCLinkmanBetween(String value1, String value2) {
            addCriterion("c_linkman between", value1, value2, "cLinkman");
            return (Criteria) this;
        }

        public Criteria andCLinkmanNotBetween(String value1, String value2) {
            addCriterion("c_linkman not between", value1, value2, "cLinkman");
            return (Criteria) this;
        }

        public Criteria andCBirthIsNull() {
            addCriterion("c_birth is null");
            return (Criteria) this;
        }

        public Criteria andCBirthIsNotNull() {
            addCriterion("c_birth is not null");
            return (Criteria) this;
        }

        public Criteria andCBirthEqualTo(String value) {
            addCriterion("c_birth =", value, "cBirth");
            return (Criteria) this;
        }

        public Criteria andCBirthNotEqualTo(String value) {
            addCriterion("c_birth <>", value, "cBirth");
            return (Criteria) this;
        }

        public Criteria andCBirthGreaterThan(String value) {
            addCriterion("c_birth >", value, "cBirth");
            return (Criteria) this;
        }

        public Criteria andCBirthGreaterThanOrEqualTo(String value) {
            addCriterion("c_birth >=", value, "cBirth");
            return (Criteria) this;
        }

        public Criteria andCBirthLessThan(String value) {
            addCriterion("c_birth <", value, "cBirth");
            return (Criteria) this;
        }

        public Criteria andCBirthLessThanOrEqualTo(String value) {
            addCriterion("c_birth <=", value, "cBirth");
            return (Criteria) this;
        }

        public Criteria andCBirthLike(String value) {
            addCriterion("c_birth like", value, "cBirth");
            return (Criteria) this;
        }

        public Criteria andCBirthNotLike(String value) {
            addCriterion("c_birth not like", value, "cBirth");
            return (Criteria) this;
        }

        public Criteria andCBirthIn(List<String> values) {
            addCriterion("c_birth in", values, "cBirth");
            return (Criteria) this;
        }

        public Criteria andCBirthNotIn(List<String> values) {
            addCriterion("c_birth not in", values, "cBirth");
            return (Criteria) this;
        }

        public Criteria andCBirthBetween(String value1, String value2) {
            addCriterion("c_birth between", value1, value2, "cBirth");
            return (Criteria) this;
        }

        public Criteria andCBirthNotBetween(String value1, String value2) {
            addCriterion("c_birth not between", value1, value2, "cBirth");
            return (Criteria) this;
        }

        public Criteria andCQqIsNull() {
            addCriterion("c_qq is null");
            return (Criteria) this;
        }

        public Criteria andCQqIsNotNull() {
            addCriterion("c_qq is not null");
            return (Criteria) this;
        }

        public Criteria andCQqEqualTo(String value) {
            addCriterion("c_qq =", value, "cQq");
            return (Criteria) this;
        }

        public Criteria andCQqNotEqualTo(String value) {
            addCriterion("c_qq <>", value, "cQq");
            return (Criteria) this;
        }

        public Criteria andCQqGreaterThan(String value) {
            addCriterion("c_qq >", value, "cQq");
            return (Criteria) this;
        }

        public Criteria andCQqGreaterThanOrEqualTo(String value) {
            addCriterion("c_qq >=", value, "cQq");
            return (Criteria) this;
        }

        public Criteria andCQqLessThan(String value) {
            addCriterion("c_qq <", value, "cQq");
            return (Criteria) this;
        }

        public Criteria andCQqLessThanOrEqualTo(String value) {
            addCriterion("c_qq <=", value, "cQq");
            return (Criteria) this;
        }

        public Criteria andCQqLike(String value) {
            addCriterion("c_qq like", value, "cQq");
            return (Criteria) this;
        }

        public Criteria andCQqNotLike(String value) {
            addCriterion("c_qq not like", value, "cQq");
            return (Criteria) this;
        }

        public Criteria andCQqIn(List<String> values) {
            addCriterion("c_qq in", values, "cQq");
            return (Criteria) this;
        }

        public Criteria andCQqNotIn(List<String> values) {
            addCriterion("c_qq not in", values, "cQq");
            return (Criteria) this;
        }

        public Criteria andCQqBetween(String value1, String value2) {
            addCriterion("c_qq between", value1, value2, "cQq");
            return (Criteria) this;
        }

        public Criteria andCQqNotBetween(String value1, String value2) {
            addCriterion("c_qq not between", value1, value2, "cQq");
            return (Criteria) this;
        }

        public Criteria andCWeiboIsNull() {
            addCriterion("c_weibo is null");
            return (Criteria) this;
        }

        public Criteria andCWeiboIsNotNull() {
            addCriterion("c_weibo is not null");
            return (Criteria) this;
        }

        public Criteria andCWeiboEqualTo(String value) {
            addCriterion("c_weibo =", value, "cWeibo");
            return (Criteria) this;
        }

        public Criteria andCWeiboNotEqualTo(String value) {
            addCriterion("c_weibo <>", value, "cWeibo");
            return (Criteria) this;
        }

        public Criteria andCWeiboGreaterThan(String value) {
            addCriterion("c_weibo >", value, "cWeibo");
            return (Criteria) this;
        }

        public Criteria andCWeiboGreaterThanOrEqualTo(String value) {
            addCriterion("c_weibo >=", value, "cWeibo");
            return (Criteria) this;
        }

        public Criteria andCWeiboLessThan(String value) {
            addCriterion("c_weibo <", value, "cWeibo");
            return (Criteria) this;
        }

        public Criteria andCWeiboLessThanOrEqualTo(String value) {
            addCriterion("c_weibo <=", value, "cWeibo");
            return (Criteria) this;
        }

        public Criteria andCWeiboLike(String value) {
            addCriterion("c_weibo like", value, "cWeibo");
            return (Criteria) this;
        }

        public Criteria andCWeiboNotLike(String value) {
            addCriterion("c_weibo not like", value, "cWeibo");
            return (Criteria) this;
        }

        public Criteria andCWeiboIn(List<String> values) {
            addCriterion("c_weibo in", values, "cWeibo");
            return (Criteria) this;
        }

        public Criteria andCWeiboNotIn(List<String> values) {
            addCriterion("c_weibo not in", values, "cWeibo");
            return (Criteria) this;
        }

        public Criteria andCWeiboBetween(String value1, String value2) {
            addCriterion("c_weibo between", value1, value2, "cWeibo");
            return (Criteria) this;
        }

        public Criteria andCWeiboNotBetween(String value1, String value2) {
            addCriterion("c_weibo not between", value1, value2, "cWeibo");
            return (Criteria) this;
        }

        public Criteria andCWechatIsNull() {
            addCriterion("c_wechat is null");
            return (Criteria) this;
        }

        public Criteria andCWechatIsNotNull() {
            addCriterion("c_wechat is not null");
            return (Criteria) this;
        }

        public Criteria andCWechatEqualTo(String value) {
            addCriterion("c_wechat =", value, "cWechat");
            return (Criteria) this;
        }

        public Criteria andCWechatNotEqualTo(String value) {
            addCriterion("c_wechat <>", value, "cWechat");
            return (Criteria) this;
        }

        public Criteria andCWechatGreaterThan(String value) {
            addCriterion("c_wechat >", value, "cWechat");
            return (Criteria) this;
        }

        public Criteria andCWechatGreaterThanOrEqualTo(String value) {
            addCriterion("c_wechat >=", value, "cWechat");
            return (Criteria) this;
        }

        public Criteria andCWechatLessThan(String value) {
            addCriterion("c_wechat <", value, "cWechat");
            return (Criteria) this;
        }

        public Criteria andCWechatLessThanOrEqualTo(String value) {
            addCriterion("c_wechat <=", value, "cWechat");
            return (Criteria) this;
        }

        public Criteria andCWechatLike(String value) {
            addCriterion("c_wechat like", value, "cWechat");
            return (Criteria) this;
        }

        public Criteria andCWechatNotLike(String value) {
            addCriterion("c_wechat not like", value, "cWechat");
            return (Criteria) this;
        }

        public Criteria andCWechatIn(List<String> values) {
            addCriterion("c_wechat in", values, "cWechat");
            return (Criteria) this;
        }

        public Criteria andCWechatNotIn(List<String> values) {
            addCriterion("c_wechat not in", values, "cWechat");
            return (Criteria) this;
        }

        public Criteria andCWechatBetween(String value1, String value2) {
            addCriterion("c_wechat between", value1, value2, "cWechat");
            return (Criteria) this;
        }

        public Criteria andCWechatNotBetween(String value1, String value2) {
            addCriterion("c_wechat not between", value1, value2, "cWechat");
            return (Criteria) this;
        }

        public Criteria andCTrdeIsNull() {
            addCriterion("c_trde is null");
            return (Criteria) this;
        }

        public Criteria andCTrdeIsNotNull() {
            addCriterion("c_trde is not null");
            return (Criteria) this;
        }

        public Criteria andCTrdeEqualTo(String value) {
            addCriterion("c_trde =", value, "cTrde");
            return (Criteria) this;
        }

        public Criteria andCTrdeNotEqualTo(String value) {
            addCriterion("c_trde <>", value, "cTrde");
            return (Criteria) this;
        }

        public Criteria andCTrdeGreaterThan(String value) {
            addCriterion("c_trde >", value, "cTrde");
            return (Criteria) this;
        }

        public Criteria andCTrdeGreaterThanOrEqualTo(String value) {
            addCriterion("c_trde >=", value, "cTrde");
            return (Criteria) this;
        }

        public Criteria andCTrdeLessThan(String value) {
            addCriterion("c_trde <", value, "cTrde");
            return (Criteria) this;
        }

        public Criteria andCTrdeLessThanOrEqualTo(String value) {
            addCriterion("c_trde <=", value, "cTrde");
            return (Criteria) this;
        }

        public Criteria andCTrdeLike(String value) {
            addCriterion("c_trde like", value, "cTrde");
            return (Criteria) this;
        }

        public Criteria andCTrdeNotLike(String value) {
            addCriterion("c_trde not like", value, "cTrde");
            return (Criteria) this;
        }

        public Criteria andCTrdeIn(List<String> values) {
            addCriterion("c_trde in", values, "cTrde");
            return (Criteria) this;
        }

        public Criteria andCTrdeNotIn(List<String> values) {
            addCriterion("c_trde not in", values, "cTrde");
            return (Criteria) this;
        }

        public Criteria andCTrdeBetween(String value1, String value2) {
            addCriterion("c_trde between", value1, value2, "cTrde");
            return (Criteria) this;
        }

        public Criteria andCTrdeNotBetween(String value1, String value2) {
            addCriterion("c_trde not between", value1, value2, "cTrde");
            return (Criteria) this;
        }

        public Criteria andCJobIsNull() {
            addCriterion("c_job is null");
            return (Criteria) this;
        }

        public Criteria andCJobIsNotNull() {
            addCriterion("c_job is not null");
            return (Criteria) this;
        }

        public Criteria andCJobEqualTo(String value) {
            addCriterion("c_job =", value, "cJob");
            return (Criteria) this;
        }

        public Criteria andCJobNotEqualTo(String value) {
            addCriterion("c_job <>", value, "cJob");
            return (Criteria) this;
        }

        public Criteria andCJobGreaterThan(String value) {
            addCriterion("c_job >", value, "cJob");
            return (Criteria) this;
        }

        public Criteria andCJobGreaterThanOrEqualTo(String value) {
            addCriterion("c_job >=", value, "cJob");
            return (Criteria) this;
        }

        public Criteria andCJobLessThan(String value) {
            addCriterion("c_job <", value, "cJob");
            return (Criteria) this;
        }

        public Criteria andCJobLessThanOrEqualTo(String value) {
            addCriterion("c_job <=", value, "cJob");
            return (Criteria) this;
        }

        public Criteria andCJobLike(String value) {
            addCriterion("c_job like", value, "cJob");
            return (Criteria) this;
        }

        public Criteria andCJobNotLike(String value) {
            addCriterion("c_job not like", value, "cJob");
            return (Criteria) this;
        }

        public Criteria andCJobIn(List<String> values) {
            addCriterion("c_job in", values, "cJob");
            return (Criteria) this;
        }

        public Criteria andCJobNotIn(List<String> values) {
            addCriterion("c_job not in", values, "cJob");
            return (Criteria) this;
        }

        public Criteria andCJobBetween(String value1, String value2) {
            addCriterion("c_job between", value1, value2, "cJob");
            return (Criteria) this;
        }

        public Criteria andCJobNotBetween(String value1, String value2) {
            addCriterion("c_job not between", value1, value2, "cJob");
            return (Criteria) this;
        }

        public Criteria andCAddressIsNull() {
            addCriterion("c_address is null");
            return (Criteria) this;
        }

        public Criteria andCAddressIsNotNull() {
            addCriterion("c_address is not null");
            return (Criteria) this;
        }

        public Criteria andCAddressEqualTo(String value) {
            addCriterion("c_address =", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressNotEqualTo(String value) {
            addCriterion("c_address <>", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressGreaterThan(String value) {
            addCriterion("c_address >", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressGreaterThanOrEqualTo(String value) {
            addCriterion("c_address >=", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressLessThan(String value) {
            addCriterion("c_address <", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressLessThanOrEqualTo(String value) {
            addCriterion("c_address <=", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressLike(String value) {
            addCriterion("c_address like", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressNotLike(String value) {
            addCriterion("c_address not like", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressIn(List<String> values) {
            addCriterion("c_address in", values, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressNotIn(List<String> values) {
            addCriterion("c_address not in", values, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressBetween(String value1, String value2) {
            addCriterion("c_address between", value1, value2, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressNotBetween(String value1, String value2) {
            addCriterion("c_address not between", value1, value2, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCResourceIsNull() {
            addCriterion("c_resource is null");
            return (Criteria) this;
        }

        public Criteria andCResourceIsNotNull() {
            addCriterion("c_resource is not null");
            return (Criteria) this;
        }

        public Criteria andCResourceEqualTo(String value) {
            addCriterion("c_resource =", value, "cResource");
            return (Criteria) this;
        }

        public Criteria andCResourceNotEqualTo(String value) {
            addCriterion("c_resource <>", value, "cResource");
            return (Criteria) this;
        }

        public Criteria andCResourceGreaterThan(String value) {
            addCriterion("c_resource >", value, "cResource");
            return (Criteria) this;
        }

        public Criteria andCResourceGreaterThanOrEqualTo(String value) {
            addCriterion("c_resource >=", value, "cResource");
            return (Criteria) this;
        }

        public Criteria andCResourceLessThan(String value) {
            addCriterion("c_resource <", value, "cResource");
            return (Criteria) this;
        }

        public Criteria andCResourceLessThanOrEqualTo(String value) {
            addCriterion("c_resource <=", value, "cResource");
            return (Criteria) this;
        }

        public Criteria andCResourceLike(String value) {
            addCriterion("c_resource like", value, "cResource");
            return (Criteria) this;
        }

        public Criteria andCResourceNotLike(String value) {
            addCriterion("c_resource not like", value, "cResource");
            return (Criteria) this;
        }

        public Criteria andCResourceIn(List<String> values) {
            addCriterion("c_resource in", values, "cResource");
            return (Criteria) this;
        }

        public Criteria andCResourceNotIn(List<String> values) {
            addCriterion("c_resource not in", values, "cResource");
            return (Criteria) this;
        }

        public Criteria andCResourceBetween(String value1, String value2) {
            addCriterion("c_resource between", value1, value2, "cResource");
            return (Criteria) this;
        }

        public Criteria andCResourceNotBetween(String value1, String value2) {
            addCriterion("c_resource not between", value1, value2, "cResource");
            return (Criteria) this;
        }

        public Criteria andCStatusIsNull() {
            addCriterion("c_status is null");
            return (Criteria) this;
        }

        public Criteria andCStatusIsNotNull() {
            addCriterion("c_status is not null");
            return (Criteria) this;
        }

        public Criteria andCStatusEqualTo(Byte value) {
            addCriterion("c_status =", value, "cStatus");
            return (Criteria) this;
        }

        public Criteria andCStatusNotEqualTo(Byte value) {
            addCriterion("c_status <>", value, "cStatus");
            return (Criteria) this;
        }

        public Criteria andCStatusGreaterThan(Byte value) {
            addCriterion("c_status >", value, "cStatus");
            return (Criteria) this;
        }

        public Criteria andCStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("c_status >=", value, "cStatus");
            return (Criteria) this;
        }

        public Criteria andCStatusLessThan(Byte value) {
            addCriterion("c_status <", value, "cStatus");
            return (Criteria) this;
        }

        public Criteria andCStatusLessThanOrEqualTo(Byte value) {
            addCriterion("c_status <=", value, "cStatus");
            return (Criteria) this;
        }

        public Criteria andCStatusIn(List<Byte> values) {
            addCriterion("c_status in", values, "cStatus");
            return (Criteria) this;
        }

        public Criteria andCStatusNotIn(List<Byte> values) {
            addCriterion("c_status not in", values, "cStatus");
            return (Criteria) this;
        }

        public Criteria andCStatusBetween(Byte value1, Byte value2) {
            addCriterion("c_status between", value1, value2, "cStatus");
            return (Criteria) this;
        }

        public Criteria andCStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("c_status not between", value1, value2, "cStatus");
            return (Criteria) this;
        }

        public Criteria andCRemarkIsNull() {
            addCriterion("c_remark is null");
            return (Criteria) this;
        }

        public Criteria andCRemarkIsNotNull() {
            addCriterion("c_remark is not null");
            return (Criteria) this;
        }

        public Criteria andCRemarkEqualTo(String value) {
            addCriterion("c_remark =", value, "cRemark");
            return (Criteria) this;
        }

        public Criteria andCRemarkNotEqualTo(String value) {
            addCriterion("c_remark <>", value, "cRemark");
            return (Criteria) this;
        }

        public Criteria andCRemarkGreaterThan(String value) {
            addCriterion("c_remark >", value, "cRemark");
            return (Criteria) this;
        }

        public Criteria andCRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("c_remark >=", value, "cRemark");
            return (Criteria) this;
        }

        public Criteria andCRemarkLessThan(String value) {
            addCriterion("c_remark <", value, "cRemark");
            return (Criteria) this;
        }

        public Criteria andCRemarkLessThanOrEqualTo(String value) {
            addCriterion("c_remark <=", value, "cRemark");
            return (Criteria) this;
        }

        public Criteria andCRemarkLike(String value) {
            addCriterion("c_remark like", value, "cRemark");
            return (Criteria) this;
        }

        public Criteria andCRemarkNotLike(String value) {
            addCriterion("c_remark not like", value, "cRemark");
            return (Criteria) this;
        }

        public Criteria andCRemarkIn(List<String> values) {
            addCriterion("c_remark in", values, "cRemark");
            return (Criteria) this;
        }

        public Criteria andCRemarkNotIn(List<String> values) {
            addCriterion("c_remark not in", values, "cRemark");
            return (Criteria) this;
        }

        public Criteria andCRemarkBetween(String value1, String value2) {
            addCriterion("c_remark between", value1, value2, "cRemark");
            return (Criteria) this;
        }

        public Criteria andCRemarkNotBetween(String value1, String value2) {
            addCriterion("c_remark not between", value1, value2, "cRemark");
            return (Criteria) this;
        }

        public Criteria andCScaleIsNull() {
            addCriterion("c_scale is null");
            return (Criteria) this;
        }

        public Criteria andCScaleIsNotNull() {
            addCriterion("c_scale is not null");
            return (Criteria) this;
        }

        public Criteria andCScaleEqualTo(String value) {
            addCriterion("c_scale =", value, "cScale");
            return (Criteria) this;
        }

        public Criteria andCScaleNotEqualTo(String value) {
            addCriterion("c_scale <>", value, "cScale");
            return (Criteria) this;
        }

        public Criteria andCScaleGreaterThan(String value) {
            addCriterion("c_scale >", value, "cScale");
            return (Criteria) this;
        }

        public Criteria andCScaleGreaterThanOrEqualTo(String value) {
            addCriterion("c_scale >=", value, "cScale");
            return (Criteria) this;
        }

        public Criteria andCScaleLessThan(String value) {
            addCriterion("c_scale <", value, "cScale");
            return (Criteria) this;
        }

        public Criteria andCScaleLessThanOrEqualTo(String value) {
            addCriterion("c_scale <=", value, "cScale");
            return (Criteria) this;
        }

        public Criteria andCScaleLike(String value) {
            addCriterion("c_scale like", value, "cScale");
            return (Criteria) this;
        }

        public Criteria andCScaleNotLike(String value) {
            addCriterion("c_scale not like", value, "cScale");
            return (Criteria) this;
        }

        public Criteria andCScaleIn(List<String> values) {
            addCriterion("c_scale in", values, "cScale");
            return (Criteria) this;
        }

        public Criteria andCScaleNotIn(List<String> values) {
            addCriterion("c_scale not in", values, "cScale");
            return (Criteria) this;
        }

        public Criteria andCScaleBetween(String value1, String value2) {
            addCriterion("c_scale between", value1, value2, "cScale");
            return (Criteria) this;
        }

        public Criteria andCScaleNotBetween(String value1, String value2) {
            addCriterion("c_scale not between", value1, value2, "cScale");
            return (Criteria) this;
        }

        public Criteria andCTimeIsNull() {
            addCriterion("c_time is null");
            return (Criteria) this;
        }

        public Criteria andCTimeIsNotNull() {
            addCriterion("c_time is not null");
            return (Criteria) this;
        }

        public Criteria andCTimeEqualTo(Date value) {
            addCriterion("c_time =", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotEqualTo(Date value) {
            addCriterion("c_time <>", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeGreaterThan(Date value) {
            addCriterion("c_time >", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("c_time >=", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeLessThan(Date value) {
            addCriterion("c_time <", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeLessThanOrEqualTo(Date value) {
            addCriterion("c_time <=", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeIn(List<Date> values) {
            addCriterion("c_time in", values, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotIn(List<Date> values) {
            addCriterion("c_time not in", values, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeBetween(Date value1, Date value2) {
            addCriterion("c_time between", value1, value2, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotBetween(Date value1, Date value2) {
            addCriterion("c_time not between", value1, value2, "cTime");
            return (Criteria) this;
        }

        public Criteria andCCapitalIsNull() {
            addCriterion("c_capital is null");
            return (Criteria) this;
        }

        public Criteria andCCapitalIsNotNull() {
            addCriterion("c_capital is not null");
            return (Criteria) this;
        }

        public Criteria andCCapitalEqualTo(String value) {
            addCriterion("c_capital =", value, "cCapital");
            return (Criteria) this;
        }

        public Criteria andCCapitalNotEqualTo(String value) {
            addCriterion("c_capital <>", value, "cCapital");
            return (Criteria) this;
        }

        public Criteria andCCapitalGreaterThan(String value) {
            addCriterion("c_capital >", value, "cCapital");
            return (Criteria) this;
        }

        public Criteria andCCapitalGreaterThanOrEqualTo(String value) {
            addCriterion("c_capital >=", value, "cCapital");
            return (Criteria) this;
        }

        public Criteria andCCapitalLessThan(String value) {
            addCriterion("c_capital <", value, "cCapital");
            return (Criteria) this;
        }

        public Criteria andCCapitalLessThanOrEqualTo(String value) {
            addCriterion("c_capital <=", value, "cCapital");
            return (Criteria) this;
        }

        public Criteria andCCapitalLike(String value) {
            addCriterion("c_capital like", value, "cCapital");
            return (Criteria) this;
        }

        public Criteria andCCapitalNotLike(String value) {
            addCriterion("c_capital not like", value, "cCapital");
            return (Criteria) this;
        }

        public Criteria andCCapitalIn(List<String> values) {
            addCriterion("c_capital in", values, "cCapital");
            return (Criteria) this;
        }

        public Criteria andCCapitalNotIn(List<String> values) {
            addCriterion("c_capital not in", values, "cCapital");
            return (Criteria) this;
        }

        public Criteria andCCapitalBetween(String value1, String value2) {
            addCriterion("c_capital between", value1, value2, "cCapital");
            return (Criteria) this;
        }

        public Criteria andCCapitalNotBetween(String value1, String value2) {
            addCriterion("c_capital not between", value1, value2, "cCapital");
            return (Criteria) this;
        }

        public Criteria andCSiteIsNull() {
            addCriterion("c_site is null");
            return (Criteria) this;
        }

        public Criteria andCSiteIsNotNull() {
            addCriterion("c_site is not null");
            return (Criteria) this;
        }

        public Criteria andCSiteEqualTo(String value) {
            addCriterion("c_site =", value, "cSite");
            return (Criteria) this;
        }

        public Criteria andCSiteNotEqualTo(String value) {
            addCriterion("c_site <>", value, "cSite");
            return (Criteria) this;
        }

        public Criteria andCSiteGreaterThan(String value) {
            addCriterion("c_site >", value, "cSite");
            return (Criteria) this;
        }

        public Criteria andCSiteGreaterThanOrEqualTo(String value) {
            addCriterion("c_site >=", value, "cSite");
            return (Criteria) this;
        }

        public Criteria andCSiteLessThan(String value) {
            addCriterion("c_site <", value, "cSite");
            return (Criteria) this;
        }

        public Criteria andCSiteLessThanOrEqualTo(String value) {
            addCriterion("c_site <=", value, "cSite");
            return (Criteria) this;
        }

        public Criteria andCSiteLike(String value) {
            addCriterion("c_site like", value, "cSite");
            return (Criteria) this;
        }

        public Criteria andCSiteNotLike(String value) {
            addCriterion("c_site not like", value, "cSite");
            return (Criteria) this;
        }

        public Criteria andCSiteIn(List<String> values) {
            addCriterion("c_site in", values, "cSite");
            return (Criteria) this;
        }

        public Criteria andCSiteNotIn(List<String> values) {
            addCriterion("c_site not in", values, "cSite");
            return (Criteria) this;
        }

        public Criteria andCSiteBetween(String value1, String value2) {
            addCriterion("c_site between", value1, value2, "cSite");
            return (Criteria) this;
        }

        public Criteria andCSiteNotBetween(String value1, String value2) {
            addCriterion("c_site not between", value1, value2, "cSite");
            return (Criteria) this;
        }

        public Criteria andCMailIsNull() {
            addCriterion("c_mail is null");
            return (Criteria) this;
        }

        public Criteria andCMailIsNotNull() {
            addCriterion("c_mail is not null");
            return (Criteria) this;
        }

        public Criteria andCMailEqualTo(String value) {
            addCriterion("c_mail =", value, "cMail");
            return (Criteria) this;
        }

        public Criteria andCMailNotEqualTo(String value) {
            addCriterion("c_mail <>", value, "cMail");
            return (Criteria) this;
        }

        public Criteria andCMailGreaterThan(String value) {
            addCriterion("c_mail >", value, "cMail");
            return (Criteria) this;
        }

        public Criteria andCMailGreaterThanOrEqualTo(String value) {
            addCriterion("c_mail >=", value, "cMail");
            return (Criteria) this;
        }

        public Criteria andCMailLessThan(String value) {
            addCriterion("c_mail <", value, "cMail");
            return (Criteria) this;
        }

        public Criteria andCMailLessThanOrEqualTo(String value) {
            addCriterion("c_mail <=", value, "cMail");
            return (Criteria) this;
        }

        public Criteria andCMailLike(String value) {
            addCriterion("c_mail like", value, "cMail");
            return (Criteria) this;
        }

        public Criteria andCMailNotLike(String value) {
            addCriterion("c_mail not like", value, "cMail");
            return (Criteria) this;
        }

        public Criteria andCMailIn(List<String> values) {
            addCriterion("c_mail in", values, "cMail");
            return (Criteria) this;
        }

        public Criteria andCMailNotIn(List<String> values) {
            addCriterion("c_mail not in", values, "cMail");
            return (Criteria) this;
        }

        public Criteria andCMailBetween(String value1, String value2) {
            addCriterion("c_mail between", value1, value2, "cMail");
            return (Criteria) this;
        }

        public Criteria andCMailNotBetween(String value1, String value2) {
            addCriterion("c_mail not between", value1, value2, "cMail");
            return (Criteria) this;
        }

        public Criteria andDelStatusIsNull() {
            addCriterion("del_status is null");
            return (Criteria) this;
        }

        public Criteria andDelStatusIsNotNull() {
            addCriterion("del_status is not null");
            return (Criteria) this;
        }

        public Criteria andDelStatusEqualTo(Byte value) {
            addCriterion("del_status =", value, "delStatus");
            return (Criteria) this;
        }
        
        public Criteria andSeaStatusEqualTo(Byte value) {
            addCriterion("sea_status =", value, "seaStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusNotEqualTo(Byte value) {
            addCriterion("del_status <>", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusGreaterThan(Byte value) {
            addCriterion("del_status >", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("del_status >=", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusLessThan(Byte value) {
            addCriterion("del_status <", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusLessThanOrEqualTo(Byte value) {
            addCriterion("del_status <=", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusIn(List<Byte> values) {
            addCriterion("del_status in", values, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusNotIn(List<Byte> values) {
            addCriterion("del_status not in", values, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusBetween(Byte value1, Byte value2) {
            addCriterion("del_status between", value1, value2, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("del_status not between", value1, value2, "delStatus");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNull() {
            addCriterion("create_name is null");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNotNull() {
            addCriterion("create_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreateNameEqualTo(String value) {
            addCriterion("create_name =", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("create_name <>", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThan(String value) {
            addCriterion("create_name >", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_name >=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThan(String value) {
            addCriterion("create_name <", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("create_name <=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLike(String value) {
            addCriterion("create_name like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotLike(String value) {
            addCriterion("create_name not like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameIn(List<String> values) {
            addCriterion("create_name in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotIn(List<String> values) {
            addCriterion("create_name not in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("create_name between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("create_name not between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNull() {
            addCriterion("update_name is null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNotNull() {
            addCriterion("update_name is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameEqualTo(String value) {
            addCriterion("update_name =", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotEqualTo(String value) {
            addCriterion("update_name <>", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThan(String value) {
            addCriterion("update_name >", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
            addCriterion("update_name >=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThan(String value) {
            addCriterion("update_name <", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThanOrEqualTo(String value) {
            addCriterion("update_name <=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLike(String value) {
            addCriterion("update_name like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotLike(String value) {
            addCriterion("update_name not like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIn(List<String> values) {
            addCriterion("update_name in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotIn(List<String> values) {
            addCriterion("update_name not in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameBetween(String value1, String value2) {
            addCriterion("update_name between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotBetween(String value1, String value2) {
            addCriterion("update_name not between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oa_customer
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}