package com.sy.modules.entity.oa;

import java.io.Serializable;
import java.util.Date;

public class OaCustomer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_id
     *
     * @mbggenerated
     */
    private Long cId;//客户id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_name
     *
     * @mbggenerated
     */
    private String cName;//客户名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.sys_user_id
     *
     * @mbggenerated
     */
    private Long sysUserId;
    
    private String sysUserName;
    private String cLuckyDay;//吉日
    private String cHotel;//酒店
    private Byte seaStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_mobile
     *
     * @mbggenerated
     */
    private String cMobile;//手机号码

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_phone
     *
     * @mbggenerated
     */
    private String cPhone;//电话号码

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_area
     *
     * @mbggenerated
     */
    private String cArea;//区域

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_linkman
     *
     * @mbggenerated
     */
    private String cLinkman;//联系人

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_birth
     *
     * @mbggenerated
     */
    private String cBirth;//生日

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_qq
     *
     * @mbggenerated
     */
    private String cQq;//qq

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_weibo
     *
     * @mbggenerated
     */
    private String cWeibo;//微博

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_wechat
     *
     * @mbggenerated
     */
    private String cWechat;//微信

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_trde
     *
     * @mbggenerated
     */
    private String cTrde;//

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_job
     *
     * @mbggenerated
     */
    private String cJob;//

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_address
     *
     * @mbggenerated
     */
    private String cAddress;//地址

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_resource
     *
     * @mbggenerated
     */
    private String cResource;//客户来源

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_status
     *
     * @mbggenerated
     */
    private Byte cStatus;//客户状态

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_remark
     *
     * @mbggenerated
     */
    private String cRemark;//备注

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_scale
     *
     * @mbggenerated
     */
    private String cScale;//客户规模，这里当作标签使用

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_time
     *
     * @mbggenerated
     */
    private Date cTime;//成立时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_capital
     *
     * @mbggenerated
     */
    private String cCapital;//注册资本

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_site
     *
     * @mbggenerated
     */
    private String cSite;//网址

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.c_mail
     *
     * @mbggenerated
     */
    private String cMail;//企业邮箱

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.del_status
     *
     * @mbggenerated
     */
    private Byte delStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.create_name
     *
     * @mbggenerated
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.update_name
     *
     * @mbggenerated
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_customer.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_customer
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_id
     *
     * @return the value of oa_customer.c_id
     *
     * @mbggenerated
     */
    public Long getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_id
     *
     * @param cId the value for oa_customer.c_id
     *
     * @mbggenerated
     */
    public void setcId(Long cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_name
     *
     * @return the value of oa_customer.c_name
     *
     * @mbggenerated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_name
     *
     * @param cName the value for oa_customer.c_name
     *
     * @mbggenerated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    public String getcLuckyDay() {
		return cLuckyDay;
	}

	public void setcLuckyDay(String cLuckyDay) {
		this.cLuckyDay = cLuckyDay;
	}

	public String getcHotel() {
		return cHotel;
	}

	public void setcHotel(String cHotel) {
		this.cHotel = cHotel;
	}

	public String getSysUserName() {
		return sysUserName;
	}

	public void setSysUserName(String sysUserName) {
		this.sysUserName = sysUserName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.sys_user_id
     *
     * @return the value of oa_customer.sys_user_id
     *
     * @mbggenerated
     */
    public Long getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.sys_user_id
     *
     * @param sysUserId the value for oa_customer.sys_user_id
     *
     * @mbggenerated
     */
    public void setSysUserId(Long sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_mobile
     *
     * @return the value of oa_customer.c_mobile
     *
     * @mbggenerated
     */
    public String getcMobile() {
        return cMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_mobile
     *
     * @param cMobile the value for oa_customer.c_mobile
     *
     * @mbggenerated
     */
    public void setcMobile(String cMobile) {
        this.cMobile = cMobile == null ? null : cMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_phone
     *
     * @return the value of oa_customer.c_phone
     *
     * @mbggenerated
     */
    public String getcPhone() {
        return cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_phone
     *
     * @param cPhone the value for oa_customer.c_phone
     *
     * @mbggenerated
     */
    public void setcPhone(String cPhone) {
        this.cPhone = cPhone == null ? null : cPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_area
     *
     * @return the value of oa_customer.c_area
     *
     * @mbggenerated
     */
    public String getcArea() {
        return cArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_area
     *
     * @param cArea the value for oa_customer.c_area
     *
     * @mbggenerated
     */
    public void setcArea(String cArea) {
        this.cArea = cArea == null ? null : cArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_linkman
     *
     * @return the value of oa_customer.c_linkman
     *
     * @mbggenerated
     */
    public String getcLinkman() {
        return cLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_linkman
     *
     * @param cLinkman the value for oa_customer.c_linkman
     *
     * @mbggenerated
     */
    public void setcLinkman(String cLinkman) {
        this.cLinkman = cLinkman == null ? null : cLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_birth
     *
     * @return the value of oa_customer.c_birth
     *
     * @mbggenerated
     */
    public String getcBirth() {
        return cBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_birth
     *
     * @param cBirth the value for oa_customer.c_birth
     *
     * @mbggenerated
     */
    public void setcBirth(String cBirth) {
        this.cBirth = cBirth == null ? null : cBirth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_qq
     *
     * @return the value of oa_customer.c_qq
     *
     * @mbggenerated
     */
    public String getcQq() {
        return cQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_qq
     *
     * @param cQq the value for oa_customer.c_qq
     *
     * @mbggenerated
     */
    public void setcQq(String cQq) {
        this.cQq = cQq == null ? null : cQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_weibo
     *
     * @return the value of oa_customer.c_weibo
     *
     * @mbggenerated
     */
    public String getcWeibo() {
        return cWeibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_weibo
     *
     * @param cWeibo the value for oa_customer.c_weibo
     *
     * @mbggenerated
     */
    public void setcWeibo(String cWeibo) {
        this.cWeibo = cWeibo == null ? null : cWeibo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_wechat
     *
     * @return the value of oa_customer.c_wechat
     *
     * @mbggenerated
     */
    public String getcWechat() {
        return cWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_wechat
     *
     * @param cWechat the value for oa_customer.c_wechat
     *
     * @mbggenerated
     */
    public void setcWechat(String cWechat) {
        this.cWechat = cWechat == null ? null : cWechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_trde
     *
     * @return the value of oa_customer.c_trde
     *
     * @mbggenerated
     */
    public String getcTrde() {
        return cTrde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_trde
     *
     * @param cTrde the value for oa_customer.c_trde
     *
     * @mbggenerated
     */
    public void setcTrde(String cTrde) {
        this.cTrde = cTrde == null ? null : cTrde.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_job
     *
     * @return the value of oa_customer.c_job
     *
     * @mbggenerated
     */
    public String getcJob() {
        return cJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_job
     *
     * @param cJob the value for oa_customer.c_job
     *
     * @mbggenerated
     */
    public void setcJob(String cJob) {
        this.cJob = cJob == null ? null : cJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_address
     *
     * @return the value of oa_customer.c_address
     *
     * @mbggenerated
     */
    public String getcAddress() {
        return cAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_address
     *
     * @param cAddress the value for oa_customer.c_address
     *
     * @mbggenerated
     */
    public void setcAddress(String cAddress) {
        this.cAddress = cAddress == null ? null : cAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_resource
     *
     * @return the value of oa_customer.c_resource
     *
     * @mbggenerated
     */
    public String getcResource() {
        return cResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_resource
     *
     * @param cResource the value for oa_customer.c_resource
     *
     * @mbggenerated
     */
    public void setcResource(String cResource) {
        this.cResource = cResource == null ? null : cResource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_status
     *
     * @return the value of oa_customer.c_status
     *
     * @mbggenerated
     */
    public Byte getcStatus() {
        return cStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_status
     *
     * @param cStatus the value for oa_customer.c_status
     *
     * @mbggenerated
     */
    public void setcStatus(Byte cStatus) {
        this.cStatus = cStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_remark
     *
     * @return the value of oa_customer.c_remark
     *
     * @mbggenerated
     */
    public String getcRemark() {
        return cRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_remark
     *
     * @param cRemark the value for oa_customer.c_remark
     *
     * @mbggenerated
     */
    public void setcRemark(String cRemark) {
        this.cRemark = cRemark == null ? null : cRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_scale
     *
     * @return the value of oa_customer.c_scale
     *
     * @mbggenerated
     */
    public String getcScale() {
        return cScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_scale
     *
     * @param cScale the value for oa_customer.c_scale
     *
     * @mbggenerated
     */
    public void setcScale(String cScale) {
        this.cScale = cScale == null ? null : cScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_time
     *
     * @return the value of oa_customer.c_time
     *
     * @mbggenerated
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_time
     *
     * @param cTime the value for oa_customer.c_time
     *
     * @mbggenerated
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_capital
     *
     * @return the value of oa_customer.c_capital
     *
     * @mbggenerated
     */
    public String getcCapital() {
        return cCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_capital
     *
     * @param cCapital the value for oa_customer.c_capital
     *
     * @mbggenerated
     */
    public void setcCapital(String cCapital) {
        this.cCapital = cCapital == null ? null : cCapital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_site
     *
     * @return the value of oa_customer.c_site
     *
     * @mbggenerated
     */
    public String getcSite() {
        return cSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_site
     *
     * @param cSite the value for oa_customer.c_site
     *
     * @mbggenerated
     */
    public void setcSite(String cSite) {
        this.cSite = cSite == null ? null : cSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.c_mail
     *
     * @return the value of oa_customer.c_mail
     *
     * @mbggenerated
     */
    public String getcMail() {
        return cMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.c_mail
     *
     * @param cMail the value for oa_customer.c_mail
     *
     * @mbggenerated
     */
    public void setcMail(String cMail) {
        this.cMail = cMail == null ? null : cMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.del_status
     *
     * @return the value of oa_customer.del_status
     *
     * @mbggenerated
     */
    public Byte getDelStatus() {
        return delStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.del_status
     *
     * @param delStatus the value for oa_customer.del_status
     *
     * @mbggenerated
     */
    public void setDelStatus(Byte delStatus) {
        this.delStatus = delStatus;
    }

    public Byte getSeaStatus() {
		return seaStatus;
	}

	public void setSeaStatus(Byte seaStatus) {
		this.seaStatus = seaStatus;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.create_name
     *
     * @return the value of oa_customer.create_name
     *
     * @mbggenerated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.create_name
     *
     * @param createName the value for oa_customer.create_name
     *
     * @mbggenerated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.create_time
     *
     * @return the value of oa_customer.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.create_time
     *
     * @param createTime the value for oa_customer.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.update_name
     *
     * @return the value of oa_customer.update_name
     *
     * @mbggenerated
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.update_name
     *
     * @param updateName the value for oa_customer.update_name
     *
     * @mbggenerated
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_customer.update_time
     *
     * @return the value of oa_customer.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_customer.update_time
     *
     * @param updateTime the value for oa_customer.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}