package com.sy.modules.entity.oa;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OaLinkmanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    public OaLinkmanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLmIdIsNull() {
            addCriterion("lm_id is null");
            return (Criteria) this;
        }

        public Criteria andLmIdIsNotNull() {
            addCriterion("lm_id is not null");
            return (Criteria) this;
        }

        public Criteria andLmIdEqualTo(Long value) {
            addCriterion("lm_id =", value, "lmId");
            return (Criteria) this;
        }

        public Criteria andLmIdNotEqualTo(Long value) {
            addCriterion("lm_id <>", value, "lmId");
            return (Criteria) this;
        }

        public Criteria andLmIdGreaterThan(Long value) {
            addCriterion("lm_id >", value, "lmId");
            return (Criteria) this;
        }

        public Criteria andLmIdGreaterThanOrEqualTo(Long value) {
            addCriterion("lm_id >=", value, "lmId");
            return (Criteria) this;
        }

        public Criteria andLmIdLessThan(Long value) {
            addCriterion("lm_id <", value, "lmId");
            return (Criteria) this;
        }

        public Criteria andLmIdLessThanOrEqualTo(Long value) {
            addCriterion("lm_id <=", value, "lmId");
            return (Criteria) this;
        }

        public Criteria andLmIdIn(List<Long> values) {
            addCriterion("lm_id in", values, "lmId");
            return (Criteria) this;
        }

        public Criteria andLmIdNotIn(List<Long> values) {
            addCriterion("lm_id not in", values, "lmId");
            return (Criteria) this;
        }

        public Criteria andLmIdBetween(Long value1, Long value2) {
            addCriterion("lm_id between", value1, value2, "lmId");
            return (Criteria) this;
        }

        public Criteria andLmIdNotBetween(Long value1, Long value2) {
            addCriterion("lm_id not between", value1, value2, "lmId");
            return (Criteria) this;
        }

        public Criteria andLmNameIsNull() {
            addCriterion("lm_name is null");
            return (Criteria) this;
        }

        public Criteria andLmNameIsNotNull() {
            addCriterion("lm_name is not null");
            return (Criteria) this;
        }

        public Criteria andLmNameEqualTo(String value) {
            addCriterion("lm_name =", value, "lmName");
            return (Criteria) this;
        }

        public Criteria andLmNameNotEqualTo(String value) {
            addCriterion("lm_name <>", value, "lmName");
            return (Criteria) this;
        }

        public Criteria andLmNameGreaterThan(String value) {
            addCriterion("lm_name >", value, "lmName");
            return (Criteria) this;
        }

        public Criteria andLmNameGreaterThanOrEqualTo(String value) {
            addCriterion("lm_name >=", value, "lmName");
            return (Criteria) this;
        }

        public Criteria andLmNameLessThan(String value) {
            addCriterion("lm_name <", value, "lmName");
            return (Criteria) this;
        }

        public Criteria andLmNameLessThanOrEqualTo(String value) {
            addCriterion("lm_name <=", value, "lmName");
            return (Criteria) this;
        }

        public Criteria andLmNameLike(String value) {
            addCriterion("lm_name like", value, "lmName");
            return (Criteria) this;
        }

        public Criteria andLmNameNotLike(String value) {
            addCriterion("lm_name not like", value, "lmName");
            return (Criteria) this;
        }

        public Criteria andLmNameIn(List<String> values) {
            addCriterion("lm_name in", values, "lmName");
            return (Criteria) this;
        }

        public Criteria andLmNameNotIn(List<String> values) {
            addCriterion("lm_name not in", values, "lmName");
            return (Criteria) this;
        }

        public Criteria andLmNameBetween(String value1, String value2) {
            addCriterion("lm_name between", value1, value2, "lmName");
            return (Criteria) this;
        }

        public Criteria andLmNameNotBetween(String value1, String value2) {
            addCriterion("lm_name not between", value1, value2, "lmName");
            return (Criteria) this;
        }

        public Criteria andCIdIsNull() {
            addCriterion("c_id is null");
            return (Criteria) this;
        }

        public Criteria andCIdIsNotNull() {
            addCriterion("c_id is not null");
            return (Criteria) this;
        }

        public Criteria andCIdEqualTo(Long value) {
            addCriterion("c_id =", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotEqualTo(Long value) {
            addCriterion("c_id <>", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThan(Long value) {
            addCriterion("c_id >", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThanOrEqualTo(Long value) {
            addCriterion("c_id >=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThan(Long value) {
            addCriterion("c_id <", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThanOrEqualTo(Long value) {
            addCriterion("c_id <=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdIn(List<Long> values) {
            addCriterion("c_id in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotIn(List<Long> values) {
            addCriterion("c_id not in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdBetween(Long value1, Long value2) {
            addCriterion("c_id between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotBetween(Long value1, Long value2) {
            addCriterion("c_id not between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdIsNull() {
            addCriterion("sys_user_id is null");
            return (Criteria) this;
        }

        public Criteria andSysUserIdIsNotNull() {
            addCriterion("sys_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andSysUserIdEqualTo(Integer value) {
            addCriterion("sys_user_id =", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotEqualTo(Integer value) {
            addCriterion("sys_user_id <>", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdGreaterThan(Integer value) {
            addCriterion("sys_user_id >", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sys_user_id >=", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdLessThan(Integer value) {
            addCriterion("sys_user_id <", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("sys_user_id <=", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdIn(List<Integer> values) {
            addCriterion("sys_user_id in", values, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotIn(List<Integer> values) {
            addCriterion("sys_user_id not in", values, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdBetween(Integer value1, Integer value2) {
            addCriterion("sys_user_id between", value1, value2, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sys_user_id not between", value1, value2, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andLmPostIsNull() {
            addCriterion("lm_post is null");
            return (Criteria) this;
        }

        public Criteria andLmPostIsNotNull() {
            addCriterion("lm_post is not null");
            return (Criteria) this;
        }

        public Criteria andLmPostEqualTo(String value) {
            addCriterion("lm_post =", value, "lmPost");
            return (Criteria) this;
        }

        public Criteria andLmPostNotEqualTo(String value) {
            addCriterion("lm_post <>", value, "lmPost");
            return (Criteria) this;
        }

        public Criteria andLmPostGreaterThan(String value) {
            addCriterion("lm_post >", value, "lmPost");
            return (Criteria) this;
        }

        public Criteria andLmPostGreaterThanOrEqualTo(String value) {
            addCriterion("lm_post >=", value, "lmPost");
            return (Criteria) this;
        }

        public Criteria andLmPostLessThan(String value) {
            addCriterion("lm_post <", value, "lmPost");
            return (Criteria) this;
        }

        public Criteria andLmPostLessThanOrEqualTo(String value) {
            addCriterion("lm_post <=", value, "lmPost");
            return (Criteria) this;
        }

        public Criteria andLmPostLike(String value) {
            addCriterion("lm_post like", value, "lmPost");
            return (Criteria) this;
        }

        public Criteria andLmPostNotLike(String value) {
            addCriterion("lm_post not like", value, "lmPost");
            return (Criteria) this;
        }

        public Criteria andLmPostIn(List<String> values) {
            addCriterion("lm_post in", values, "lmPost");
            return (Criteria) this;
        }

        public Criteria andLmPostNotIn(List<String> values) {
            addCriterion("lm_post not in", values, "lmPost");
            return (Criteria) this;
        }

        public Criteria andLmPostBetween(String value1, String value2) {
            addCriterion("lm_post between", value1, value2, "lmPost");
            return (Criteria) this;
        }

        public Criteria andLmPostNotBetween(String value1, String value2) {
            addCriterion("lm_post not between", value1, value2, "lmPost");
            return (Criteria) this;
        }

        public Criteria andLmEmailIsNull() {
            addCriterion("lm_email is null");
            return (Criteria) this;
        }

        public Criteria andLmEmailIsNotNull() {
            addCriterion("lm_email is not null");
            return (Criteria) this;
        }

        public Criteria andLmEmailEqualTo(String value) {
            addCriterion("lm_email =", value, "lmEmail");
            return (Criteria) this;
        }

        public Criteria andLmEmailNotEqualTo(String value) {
            addCriterion("lm_email <>", value, "lmEmail");
            return (Criteria) this;
        }

        public Criteria andLmEmailGreaterThan(String value) {
            addCriterion("lm_email >", value, "lmEmail");
            return (Criteria) this;
        }

        public Criteria andLmEmailGreaterThanOrEqualTo(String value) {
            addCriterion("lm_email >=", value, "lmEmail");
            return (Criteria) this;
        }

        public Criteria andLmEmailLessThan(String value) {
            addCriterion("lm_email <", value, "lmEmail");
            return (Criteria) this;
        }

        public Criteria andLmEmailLessThanOrEqualTo(String value) {
            addCriterion("lm_email <=", value, "lmEmail");
            return (Criteria) this;
        }

        public Criteria andLmEmailLike(String value) {
            addCriterion("lm_email like", value, "lmEmail");
            return (Criteria) this;
        }

        public Criteria andLmEmailNotLike(String value) {
            addCriterion("lm_email not like", value, "lmEmail");
            return (Criteria) this;
        }

        public Criteria andLmEmailIn(List<String> values) {
            addCriterion("lm_email in", values, "lmEmail");
            return (Criteria) this;
        }

        public Criteria andLmEmailNotIn(List<String> values) {
            addCriterion("lm_email not in", values, "lmEmail");
            return (Criteria) this;
        }

        public Criteria andLmEmailBetween(String value1, String value2) {
            addCriterion("lm_email between", value1, value2, "lmEmail");
            return (Criteria) this;
        }

        public Criteria andLmEmailNotBetween(String value1, String value2) {
            addCriterion("lm_email not between", value1, value2, "lmEmail");
            return (Criteria) this;
        }

        public Criteria andLmQqIsNull() {
            addCriterion("lm_qq is null");
            return (Criteria) this;
        }

        public Criteria andLmQqIsNotNull() {
            addCriterion("lm_qq is not null");
            return (Criteria) this;
        }

        public Criteria andLmQqEqualTo(String value) {
            addCriterion("lm_qq =", value, "lmQq");
            return (Criteria) this;
        }

        public Criteria andLmQqNotEqualTo(String value) {
            addCriterion("lm_qq <>", value, "lmQq");
            return (Criteria) this;
        }

        public Criteria andLmQqGreaterThan(String value) {
            addCriterion("lm_qq >", value, "lmQq");
            return (Criteria) this;
        }

        public Criteria andLmQqGreaterThanOrEqualTo(String value) {
            addCriterion("lm_qq >=", value, "lmQq");
            return (Criteria) this;
        }

        public Criteria andLmQqLessThan(String value) {
            addCriterion("lm_qq <", value, "lmQq");
            return (Criteria) this;
        }

        public Criteria andLmQqLessThanOrEqualTo(String value) {
            addCriterion("lm_qq <=", value, "lmQq");
            return (Criteria) this;
        }

        public Criteria andLmQqLike(String value) {
            addCriterion("lm_qq like", value, "lmQq");
            return (Criteria) this;
        }

        public Criteria andLmQqNotLike(String value) {
            addCriterion("lm_qq not like", value, "lmQq");
            return (Criteria) this;
        }

        public Criteria andLmQqIn(List<String> values) {
            addCriterion("lm_qq in", values, "lmQq");
            return (Criteria) this;
        }

        public Criteria andLmQqNotIn(List<String> values) {
            addCriterion("lm_qq not in", values, "lmQq");
            return (Criteria) this;
        }

        public Criteria andLmQqBetween(String value1, String value2) {
            addCriterion("lm_qq between", value1, value2, "lmQq");
            return (Criteria) this;
        }

        public Criteria andLmQqNotBetween(String value1, String value2) {
            addCriterion("lm_qq not between", value1, value2, "lmQq");
            return (Criteria) this;
        }

        public Criteria andLmWechatIsNull() {
            addCriterion("lm_wechat is null");
            return (Criteria) this;
        }

        public Criteria andLmWechatIsNotNull() {
            addCriterion("lm_wechat is not null");
            return (Criteria) this;
        }

        public Criteria andLmWechatEqualTo(String value) {
            addCriterion("lm_wechat =", value, "lmWechat");
            return (Criteria) this;
        }

        public Criteria andLmWechatNotEqualTo(String value) {
            addCriterion("lm_wechat <>", value, "lmWechat");
            return (Criteria) this;
        }

        public Criteria andLmWechatGreaterThan(String value) {
            addCriterion("lm_wechat >", value, "lmWechat");
            return (Criteria) this;
        }

        public Criteria andLmWechatGreaterThanOrEqualTo(String value) {
            addCriterion("lm_wechat >=", value, "lmWechat");
            return (Criteria) this;
        }

        public Criteria andLmWechatLessThan(String value) {
            addCriterion("lm_wechat <", value, "lmWechat");
            return (Criteria) this;
        }

        public Criteria andLmWechatLessThanOrEqualTo(String value) {
            addCriterion("lm_wechat <=", value, "lmWechat");
            return (Criteria) this;
        }

        public Criteria andLmWechatLike(String value) {
            addCriterion("lm_wechat like", value, "lmWechat");
            return (Criteria) this;
        }

        public Criteria andLmWechatNotLike(String value) {
            addCriterion("lm_wechat not like", value, "lmWechat");
            return (Criteria) this;
        }

        public Criteria andLmWechatIn(List<String> values) {
            addCriterion("lm_wechat in", values, "lmWechat");
            return (Criteria) this;
        }

        public Criteria andLmWechatNotIn(List<String> values) {
            addCriterion("lm_wechat not in", values, "lmWechat");
            return (Criteria) this;
        }

        public Criteria andLmWechatBetween(String value1, String value2) {
            addCriterion("lm_wechat between", value1, value2, "lmWechat");
            return (Criteria) this;
        }

        public Criteria andLmWechatNotBetween(String value1, String value2) {
            addCriterion("lm_wechat not between", value1, value2, "lmWechat");
            return (Criteria) this;
        }

        public Criteria andLmMobileIsNull() {
            addCriterion("lm_mobile is null");
            return (Criteria) this;
        }

        public Criteria andLmMobileIsNotNull() {
            addCriterion("lm_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andLmMobileEqualTo(String value) {
            addCriterion("lm_mobile =", value, "lmMobile");
            return (Criteria) this;
        }

        public Criteria andLmMobileNotEqualTo(String value) {
            addCriterion("lm_mobile <>", value, "lmMobile");
            return (Criteria) this;
        }

        public Criteria andLmMobileGreaterThan(String value) {
            addCriterion("lm_mobile >", value, "lmMobile");
            return (Criteria) this;
        }

        public Criteria andLmMobileGreaterThanOrEqualTo(String value) {
            addCriterion("lm_mobile >=", value, "lmMobile");
            return (Criteria) this;
        }

        public Criteria andLmMobileLessThan(String value) {
            addCriterion("lm_mobile <", value, "lmMobile");
            return (Criteria) this;
        }

        public Criteria andLmMobileLessThanOrEqualTo(String value) {
            addCriterion("lm_mobile <=", value, "lmMobile");
            return (Criteria) this;
        }

        public Criteria andLmMobileLike(String value) {
            addCriterion("lm_mobile like", value, "lmMobile");
            return (Criteria) this;
        }

        public Criteria andLmMobileNotLike(String value) {
            addCriterion("lm_mobile not like", value, "lmMobile");
            return (Criteria) this;
        }

        public Criteria andLmMobileIn(List<String> values) {
            addCriterion("lm_mobile in", values, "lmMobile");
            return (Criteria) this;
        }

        public Criteria andLmMobileNotIn(List<String> values) {
            addCriterion("lm_mobile not in", values, "lmMobile");
            return (Criteria) this;
        }

        public Criteria andLmMobileBetween(String value1, String value2) {
            addCriterion("lm_mobile between", value1, value2, "lmMobile");
            return (Criteria) this;
        }

        public Criteria andLmMobileNotBetween(String value1, String value2) {
            addCriterion("lm_mobile not between", value1, value2, "lmMobile");
            return (Criteria) this;
        }

        public Criteria andLmPhone1IsNull() {
            addCriterion("lm_phone1 is null");
            return (Criteria) this;
        }

        public Criteria andLmPhone1IsNotNull() {
            addCriterion("lm_phone1 is not null");
            return (Criteria) this;
        }

        public Criteria andLmPhone1EqualTo(String value) {
            addCriterion("lm_phone1 =", value, "lmPhone1");
            return (Criteria) this;
        }

        public Criteria andLmPhone1NotEqualTo(String value) {
            addCriterion("lm_phone1 <>", value, "lmPhone1");
            return (Criteria) this;
        }

        public Criteria andLmPhone1GreaterThan(String value) {
            addCriterion("lm_phone1 >", value, "lmPhone1");
            return (Criteria) this;
        }

        public Criteria andLmPhone1GreaterThanOrEqualTo(String value) {
            addCriterion("lm_phone1 >=", value, "lmPhone1");
            return (Criteria) this;
        }

        public Criteria andLmPhone1LessThan(String value) {
            addCriterion("lm_phone1 <", value, "lmPhone1");
            return (Criteria) this;
        }

        public Criteria andLmPhone1LessThanOrEqualTo(String value) {
            addCriterion("lm_phone1 <=", value, "lmPhone1");
            return (Criteria) this;
        }

        public Criteria andLmPhone1Like(String value) {
            addCriterion("lm_phone1 like", value, "lmPhone1");
            return (Criteria) this;
        }

        public Criteria andLmPhone1NotLike(String value) {
            addCriterion("lm_phone1 not like", value, "lmPhone1");
            return (Criteria) this;
        }

        public Criteria andLmPhone1In(List<String> values) {
            addCriterion("lm_phone1 in", values, "lmPhone1");
            return (Criteria) this;
        }

        public Criteria andLmPhone1NotIn(List<String> values) {
            addCriterion("lm_phone1 not in", values, "lmPhone1");
            return (Criteria) this;
        }

        public Criteria andLmPhone1Between(String value1, String value2) {
            addCriterion("lm_phone1 between", value1, value2, "lmPhone1");
            return (Criteria) this;
        }

        public Criteria andLmPhone1NotBetween(String value1, String value2) {
            addCriterion("lm_phone1 not between", value1, value2, "lmPhone1");
            return (Criteria) this;
        }

        public Criteria andLmPhone2IsNull() {
            addCriterion("lm_phone2 is null");
            return (Criteria) this;
        }

        public Criteria andLmPhone2IsNotNull() {
            addCriterion("lm_phone2 is not null");
            return (Criteria) this;
        }

        public Criteria andLmPhone2EqualTo(String value) {
            addCriterion("lm_phone2 =", value, "lmPhone2");
            return (Criteria) this;
        }

        public Criteria andLmPhone2NotEqualTo(String value) {
            addCriterion("lm_phone2 <>", value, "lmPhone2");
            return (Criteria) this;
        }

        public Criteria andLmPhone2GreaterThan(String value) {
            addCriterion("lm_phone2 >", value, "lmPhone2");
            return (Criteria) this;
        }

        public Criteria andLmPhone2GreaterThanOrEqualTo(String value) {
            addCriterion("lm_phone2 >=", value, "lmPhone2");
            return (Criteria) this;
        }

        public Criteria andLmPhone2LessThan(String value) {
            addCriterion("lm_phone2 <", value, "lmPhone2");
            return (Criteria) this;
        }

        public Criteria andLmPhone2LessThanOrEqualTo(String value) {
            addCriterion("lm_phone2 <=", value, "lmPhone2");
            return (Criteria) this;
        }

        public Criteria andLmPhone2Like(String value) {
            addCriterion("lm_phone2 like", value, "lmPhone2");
            return (Criteria) this;
        }

        public Criteria andLmPhone2NotLike(String value) {
            addCriterion("lm_phone2 not like", value, "lmPhone2");
            return (Criteria) this;
        }

        public Criteria andLmPhone2In(List<String> values) {
            addCriterion("lm_phone2 in", values, "lmPhone2");
            return (Criteria) this;
        }

        public Criteria andLmPhone2NotIn(List<String> values) {
            addCriterion("lm_phone2 not in", values, "lmPhone2");
            return (Criteria) this;
        }

        public Criteria andLmPhone2Between(String value1, String value2) {
            addCriterion("lm_phone2 between", value1, value2, "lmPhone2");
            return (Criteria) this;
        }

        public Criteria andLmPhone2NotBetween(String value1, String value2) {
            addCriterion("lm_phone2 not between", value1, value2, "lmPhone2");
            return (Criteria) this;
        }

        public Criteria andLmPhone3IsNull() {
            addCriterion("lm_phone3 is null");
            return (Criteria) this;
        }

        public Criteria andLmPhone3IsNotNull() {
            addCriterion("lm_phone3 is not null");
            return (Criteria) this;
        }

        public Criteria andLmPhone3EqualTo(String value) {
            addCriterion("lm_phone3 =", value, "lmPhone3");
            return (Criteria) this;
        }

        public Criteria andLmPhone3NotEqualTo(String value) {
            addCriterion("lm_phone3 <>", value, "lmPhone3");
            return (Criteria) this;
        }

        public Criteria andLmPhone3GreaterThan(String value) {
            addCriterion("lm_phone3 >", value, "lmPhone3");
            return (Criteria) this;
        }

        public Criteria andLmPhone3GreaterThanOrEqualTo(String value) {
            addCriterion("lm_phone3 >=", value, "lmPhone3");
            return (Criteria) this;
        }

        public Criteria andLmPhone3LessThan(String value) {
            addCriterion("lm_phone3 <", value, "lmPhone3");
            return (Criteria) this;
        }

        public Criteria andLmPhone3LessThanOrEqualTo(String value) {
            addCriterion("lm_phone3 <=", value, "lmPhone3");
            return (Criteria) this;
        }

        public Criteria andLmPhone3Like(String value) {
            addCriterion("lm_phone3 like", value, "lmPhone3");
            return (Criteria) this;
        }

        public Criteria andLmPhone3NotLike(String value) {
            addCriterion("lm_phone3 not like", value, "lmPhone3");
            return (Criteria) this;
        }

        public Criteria andLmPhone3In(List<String> values) {
            addCriterion("lm_phone3 in", values, "lmPhone3");
            return (Criteria) this;
        }

        public Criteria andLmPhone3NotIn(List<String> values) {
            addCriterion("lm_phone3 not in", values, "lmPhone3");
            return (Criteria) this;
        }

        public Criteria andLmPhone3Between(String value1, String value2) {
            addCriterion("lm_phone3 between", value1, value2, "lmPhone3");
            return (Criteria) this;
        }

        public Criteria andLmPhone3NotBetween(String value1, String value2) {
            addCriterion("lm_phone3 not between", value1, value2, "lmPhone3");
            return (Criteria) this;
        }

        public Criteria andLmPhone4IsNull() {
            addCriterion("lm_phone4 is null");
            return (Criteria) this;
        }

        public Criteria andLmPhone4IsNotNull() {
            addCriterion("lm_phone4 is not null");
            return (Criteria) this;
        }

        public Criteria andLmPhone4EqualTo(String value) {
            addCriterion("lm_phone4 =", value, "lmPhone4");
            return (Criteria) this;
        }

        public Criteria andLmPhone4NotEqualTo(String value) {
            addCriterion("lm_phone4 <>", value, "lmPhone4");
            return (Criteria) this;
        }

        public Criteria andLmPhone4GreaterThan(String value) {
            addCriterion("lm_phone4 >", value, "lmPhone4");
            return (Criteria) this;
        }

        public Criteria andLmPhone4GreaterThanOrEqualTo(String value) {
            addCriterion("lm_phone4 >=", value, "lmPhone4");
            return (Criteria) this;
        }

        public Criteria andLmPhone4LessThan(String value) {
            addCriterion("lm_phone4 <", value, "lmPhone4");
            return (Criteria) this;
        }

        public Criteria andLmPhone4LessThanOrEqualTo(String value) {
            addCriterion("lm_phone4 <=", value, "lmPhone4");
            return (Criteria) this;
        }

        public Criteria andLmPhone4Like(String value) {
            addCriterion("lm_phone4 like", value, "lmPhone4");
            return (Criteria) this;
        }

        public Criteria andLmPhone4NotLike(String value) {
            addCriterion("lm_phone4 not like", value, "lmPhone4");
            return (Criteria) this;
        }

        public Criteria andLmPhone4In(List<String> values) {
            addCriterion("lm_phone4 in", values, "lmPhone4");
            return (Criteria) this;
        }

        public Criteria andLmPhone4NotIn(List<String> values) {
            addCriterion("lm_phone4 not in", values, "lmPhone4");
            return (Criteria) this;
        }

        public Criteria andLmPhone4Between(String value1, String value2) {
            addCriterion("lm_phone4 between", value1, value2, "lmPhone4");
            return (Criteria) this;
        }

        public Criteria andLmPhone4NotBetween(String value1, String value2) {
            addCriterion("lm_phone4 not between", value1, value2, "lmPhone4");
            return (Criteria) this;
        }

        public Criteria andLmPhone5IsNull() {
            addCriterion("lm_phone5 is null");
            return (Criteria) this;
        }

        public Criteria andLmPhone5IsNotNull() {
            addCriterion("lm_phone5 is not null");
            return (Criteria) this;
        }

        public Criteria andLmPhone5EqualTo(String value) {
            addCriterion("lm_phone5 =", value, "lmPhone5");
            return (Criteria) this;
        }

        public Criteria andLmPhone5NotEqualTo(String value) {
            addCriterion("lm_phone5 <>", value, "lmPhone5");
            return (Criteria) this;
        }

        public Criteria andLmPhone5GreaterThan(String value) {
            addCriterion("lm_phone5 >", value, "lmPhone5");
            return (Criteria) this;
        }

        public Criteria andLmPhone5GreaterThanOrEqualTo(String value) {
            addCriterion("lm_phone5 >=", value, "lmPhone5");
            return (Criteria) this;
        }

        public Criteria andLmPhone5LessThan(String value) {
            addCriterion("lm_phone5 <", value, "lmPhone5");
            return (Criteria) this;
        }

        public Criteria andLmPhone5LessThanOrEqualTo(String value) {
            addCriterion("lm_phone5 <=", value, "lmPhone5");
            return (Criteria) this;
        }

        public Criteria andLmPhone5Like(String value) {
            addCriterion("lm_phone5 like", value, "lmPhone5");
            return (Criteria) this;
        }

        public Criteria andLmPhone5NotLike(String value) {
            addCriterion("lm_phone5 not like", value, "lmPhone5");
            return (Criteria) this;
        }

        public Criteria andLmPhone5In(List<String> values) {
            addCriterion("lm_phone5 in", values, "lmPhone5");
            return (Criteria) this;
        }

        public Criteria andLmPhone5NotIn(List<String> values) {
            addCriterion("lm_phone5 not in", values, "lmPhone5");
            return (Criteria) this;
        }

        public Criteria andLmPhone5Between(String value1, String value2) {
            addCriterion("lm_phone5 between", value1, value2, "lmPhone5");
            return (Criteria) this;
        }

        public Criteria andLmPhone5NotBetween(String value1, String value2) {
            addCriterion("lm_phone5 not between", value1, value2, "lmPhone5");
            return (Criteria) this;
        }

        public Criteria andLmPhone6IsNull() {
            addCriterion("lm_phone6 is null");
            return (Criteria) this;
        }

        public Criteria andLmPhone6IsNotNull() {
            addCriterion("lm_phone6 is not null");
            return (Criteria) this;
        }

        public Criteria andLmPhone6EqualTo(String value) {
            addCriterion("lm_phone6 =", value, "lmPhone6");
            return (Criteria) this;
        }

        public Criteria andLmPhone6NotEqualTo(String value) {
            addCriterion("lm_phone6 <>", value, "lmPhone6");
            return (Criteria) this;
        }

        public Criteria andLmPhone6GreaterThan(String value) {
            addCriterion("lm_phone6 >", value, "lmPhone6");
            return (Criteria) this;
        }

        public Criteria andLmPhone6GreaterThanOrEqualTo(String value) {
            addCriterion("lm_phone6 >=", value, "lmPhone6");
            return (Criteria) this;
        }

        public Criteria andLmPhone6LessThan(String value) {
            addCriterion("lm_phone6 <", value, "lmPhone6");
            return (Criteria) this;
        }

        public Criteria andLmPhone6LessThanOrEqualTo(String value) {
            addCriterion("lm_phone6 <=", value, "lmPhone6");
            return (Criteria) this;
        }

        public Criteria andLmPhone6Like(String value) {
            addCriterion("lm_phone6 like", value, "lmPhone6");
            return (Criteria) this;
        }

        public Criteria andLmPhone6NotLike(String value) {
            addCriterion("lm_phone6 not like", value, "lmPhone6");
            return (Criteria) this;
        }

        public Criteria andLmPhone6In(List<String> values) {
            addCriterion("lm_phone6 in", values, "lmPhone6");
            return (Criteria) this;
        }

        public Criteria andLmPhone6NotIn(List<String> values) {
            addCriterion("lm_phone6 not in", values, "lmPhone6");
            return (Criteria) this;
        }

        public Criteria andLmPhone6Between(String value1, String value2) {
            addCriterion("lm_phone6 between", value1, value2, "lmPhone6");
            return (Criteria) this;
        }

        public Criteria andLmPhone6NotBetween(String value1, String value2) {
            addCriterion("lm_phone6 not between", value1, value2, "lmPhone6");
            return (Criteria) this;
        }

        public Criteria andLmBirthIsNull() {
            addCriterion("lm_birth is null");
            return (Criteria) this;
        }

        public Criteria andLmBirthIsNotNull() {
            addCriterion("lm_birth is not null");
            return (Criteria) this;
        }

        public Criteria andLmBirthEqualTo(String value) {
            addCriterion("lm_birth =", value, "lmBirth");
            return (Criteria) this;
        }

        public Criteria andLmBirthNotEqualTo(String value) {
            addCriterion("lm_birth <>", value, "lmBirth");
            return (Criteria) this;
        }

        public Criteria andLmBirthGreaterThan(String value) {
            addCriterion("lm_birth >", value, "lmBirth");
            return (Criteria) this;
        }

        public Criteria andLmBirthGreaterThanOrEqualTo(String value) {
            addCriterion("lm_birth >=", value, "lmBirth");
            return (Criteria) this;
        }

        public Criteria andLmBirthLessThan(String value) {
            addCriterion("lm_birth <", value, "lmBirth");
            return (Criteria) this;
        }

        public Criteria andLmBirthLessThanOrEqualTo(String value) {
            addCriterion("lm_birth <=", value, "lmBirth");
            return (Criteria) this;
        }

        public Criteria andLmBirthLike(String value) {
            addCriterion("lm_birth like", value, "lmBirth");
            return (Criteria) this;
        }

        public Criteria andLmBirthNotLike(String value) {
            addCriterion("lm_birth not like", value, "lmBirth");
            return (Criteria) this;
        }

        public Criteria andLmBirthIn(List<String> values) {
            addCriterion("lm_birth in", values, "lmBirth");
            return (Criteria) this;
        }

        public Criteria andLmBirthNotIn(List<String> values) {
            addCriterion("lm_birth not in", values, "lmBirth");
            return (Criteria) this;
        }

        public Criteria andLmBirthBetween(String value1, String value2) {
            addCriterion("lm_birth between", value1, value2, "lmBirth");
            return (Criteria) this;
        }

        public Criteria andLmBirthNotBetween(String value1, String value2) {
            addCriterion("lm_birth not between", value1, value2, "lmBirth");
            return (Criteria) this;
        }

        public Criteria andDelStatusIsNull() {
            addCriterion("del_status is null");
            return (Criteria) this;
        }

        public Criteria andDelStatusIsNotNull() {
            addCriterion("del_status is not null");
            return (Criteria) this;
        }

        public Criteria andDelStatusEqualTo(Byte value) {
            addCriterion("del_status =", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusNotEqualTo(Byte value) {
            addCriterion("del_status <>", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusGreaterThan(Byte value) {
            addCriterion("del_status >", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("del_status >=", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusLessThan(Byte value) {
            addCriterion("del_status <", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusLessThanOrEqualTo(Byte value) {
            addCriterion("del_status <=", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusIn(List<Byte> values) {
            addCriterion("del_status in", values, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusNotIn(List<Byte> values) {
            addCriterion("del_status not in", values, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusBetween(Byte value1, Byte value2) {
            addCriterion("del_status between", value1, value2, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("del_status not between", value1, value2, "delStatus");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNull() {
            addCriterion("create_name is null");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNotNull() {
            addCriterion("create_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreateNameEqualTo(String value) {
            addCriterion("create_name =", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("create_name <>", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThan(String value) {
            addCriterion("create_name >", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_name >=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThan(String value) {
            addCriterion("create_name <", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("create_name <=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLike(String value) {
            addCriterion("create_name like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotLike(String value) {
            addCriterion("create_name not like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameIn(List<String> values) {
            addCriterion("create_name in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotIn(List<String> values) {
            addCriterion("create_name not in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("create_name between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("create_name not between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNull() {
            addCriterion("update_name is null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNotNull() {
            addCriterion("update_name is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameEqualTo(String value) {
            addCriterion("update_name =", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotEqualTo(String value) {
            addCriterion("update_name <>", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThan(String value) {
            addCriterion("update_name >", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
            addCriterion("update_name >=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThan(String value) {
            addCriterion("update_name <", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThanOrEqualTo(String value) {
            addCriterion("update_name <=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLike(String value) {
            addCriterion("update_name like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotLike(String value) {
            addCriterion("update_name not like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIn(List<String> values) {
            addCriterion("update_name in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotIn(List<String> values) {
            addCriterion("update_name not in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameBetween(String value1, String value2) {
            addCriterion("update_name between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotBetween(String value1, String value2) {
            addCriterion("update_name not between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oa_linkman
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oa_linkman
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}