package com.sy.modules.entity.oa;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OaRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    public OaRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRIdIsNull() {
            addCriterion("r_id is null");
            return (Criteria) this;
        }

        public Criteria andRIdIsNotNull() {
            addCriterion("r_id is not null");
            return (Criteria) this;
        }

        public Criteria andRIdEqualTo(Long value) {
            addCriterion("r_id =", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdNotEqualTo(Long value) {
            addCriterion("r_id <>", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdGreaterThan(Long value) {
            addCriterion("r_id >", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdGreaterThanOrEqualTo(Long value) {
            addCriterion("r_id >=", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdLessThan(Long value) {
            addCriterion("r_id <", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdLessThanOrEqualTo(Long value) {
            addCriterion("r_id <=", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdIn(List<Long> values) {
            addCriterion("r_id in", values, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdNotIn(List<Long> values) {
            addCriterion("r_id not in", values, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdBetween(Long value1, Long value2) {
            addCriterion("r_id between", value1, value2, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdNotBetween(Long value1, Long value2) {
            addCriterion("r_id not between", value1, value2, "rId");
            return (Criteria) this;
        }

        public Criteria andCIdIsNull() {
            addCriterion("c_id is null");
            return (Criteria) this;
        }

        public Criteria andCIdIsNotNull() {
            addCriterion("c_id is not null");
            return (Criteria) this;
        }

        public Criteria andCIdEqualTo(Long value) {
            addCriterion("c_id =", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotEqualTo(Long value) {
            addCriterion("c_id <>", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThan(Long value) {
            addCriterion("c_id >", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThanOrEqualTo(Long value) {
            addCriterion("c_id >=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThan(Long value) {
            addCriterion("c_id <", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThanOrEqualTo(Long value) {
            addCriterion("c_id <=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdIn(List<Long> values) {
            addCriterion("c_id in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotIn(List<Long> values) {
            addCriterion("c_id not in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdBetween(Long value1, Long value2) {
            addCriterion("c_id between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotBetween(Long value1, Long value2) {
            addCriterion("c_id not between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andRCustomerIsNull() {
            addCriterion("r_customer is null");
            return (Criteria) this;
        }

        public Criteria andRCustomerIsNotNull() {
            addCriterion("r_customer is not null");
            return (Criteria) this;
        }

        public Criteria andRCustomerEqualTo(String value) {
            addCriterion("r_customer =", value, "rCustomer");
            return (Criteria) this;
        }

        public Criteria andRCustomerNotEqualTo(String value) {
            addCriterion("r_customer <>", value, "rCustomer");
            return (Criteria) this;
        }

        public Criteria andRCustomerGreaterThan(String value) {
            addCriterion("r_customer >", value, "rCustomer");
            return (Criteria) this;
        }

        public Criteria andRCustomerGreaterThanOrEqualTo(String value) {
            addCriterion("r_customer >=", value, "rCustomer");
            return (Criteria) this;
        }

        public Criteria andRCustomerLessThan(String value) {
            addCriterion("r_customer <", value, "rCustomer");
            return (Criteria) this;
        }

        public Criteria andRCustomerLessThanOrEqualTo(String value) {
            addCriterion("r_customer <=", value, "rCustomer");
            return (Criteria) this;
        }

        public Criteria andRCustomerLike(String value) {
            addCriterion("r_customer like", value, "rCustomer");
            return (Criteria) this;
        }

        public Criteria andRCustomerNotLike(String value) {
            addCriterion("r_customer not like", value, "rCustomer");
            return (Criteria) this;
        }

        public Criteria andRCustomerIn(List<String> values) {
            addCriterion("r_customer in", values, "rCustomer");
            return (Criteria) this;
        }

        public Criteria andRCustomerNotIn(List<String> values) {
            addCriterion("r_customer not in", values, "rCustomer");
            return (Criteria) this;
        }

        public Criteria andRCustomerBetween(String value1, String value2) {
            addCriterion("r_customer between", value1, value2, "rCustomer");
            return (Criteria) this;
        }

        public Criteria andRCustomerNotBetween(String value1, String value2) {
            addCriterion("r_customer not between", value1, value2, "rCustomer");
            return (Criteria) this;
        }

        public Criteria andRModeIsNull() {
            addCriterion("r_mode is null");
            return (Criteria) this;
        }

        public Criteria andRModeIsNotNull() {
            addCriterion("r_mode is not null");
            return (Criteria) this;
        }

        public Criteria andRModeEqualTo(Byte value) {
            addCriterion("r_mode =", value, "rMode");
            return (Criteria) this;
        }

        public Criteria andRModeNotEqualTo(Byte value) {
            addCriterion("r_mode <>", value, "rMode");
            return (Criteria) this;
        }

        public Criteria andRModeGreaterThan(Byte value) {
            addCriterion("r_mode >", value, "rMode");
            return (Criteria) this;
        }

        public Criteria andRModeGreaterThanOrEqualTo(Byte value) {
            addCriterion("r_mode >=", value, "rMode");
            return (Criteria) this;
        }

        public Criteria andRModeLessThan(Byte value) {
            addCriterion("r_mode <", value, "rMode");
            return (Criteria) this;
        }

        public Criteria andRModeLessThanOrEqualTo(Byte value) {
            addCriterion("r_mode <=", value, "rMode");
            return (Criteria) this;
        }

        public Criteria andRModeIn(List<Byte> values) {
            addCriterion("r_mode in", values, "rMode");
            return (Criteria) this;
        }

        public Criteria andRModeNotIn(List<Byte> values) {
            addCriterion("r_mode not in", values, "rMode");
            return (Criteria) this;
        }

        public Criteria andRModeBetween(Byte value1, Byte value2) {
            addCriterion("r_mode between", value1, value2, "rMode");
            return (Criteria) this;
        }

        public Criteria andRModeNotBetween(Byte value1, Byte value2) {
            addCriterion("r_mode not between", value1, value2, "rMode");
            return (Criteria) this;
        }

        public Criteria andRMainThingIsNull() {
            addCriterion("r_main_thing is null");
            return (Criteria) this;
        }

        public Criteria andRMainThingIsNotNull() {
            addCriterion("r_main_thing is not null");
            return (Criteria) this;
        }

        public Criteria andRMainThingEqualTo(Byte value) {
            addCriterion("r_main_thing =", value, "rMainThing");
            return (Criteria) this;
        }

        public Criteria andRMainThingNotEqualTo(Byte value) {
            addCriterion("r_main_thing <>", value, "rMainThing");
            return (Criteria) this;
        }

        public Criteria andRMainThingGreaterThan(Byte value) {
            addCriterion("r_main_thing >", value, "rMainThing");
            return (Criteria) this;
        }

        public Criteria andRMainThingGreaterThanOrEqualTo(Byte value) {
            addCriterion("r_main_thing >=", value, "rMainThing");
            return (Criteria) this;
        }

        public Criteria andRMainThingLessThan(Byte value) {
            addCriterion("r_main_thing <", value, "rMainThing");
            return (Criteria) this;
        }

        public Criteria andRMainThingLessThanOrEqualTo(Byte value) {
            addCriterion("r_main_thing <=", value, "rMainThing");
            return (Criteria) this;
        }

        public Criteria andRMainThingIn(List<Byte> values) {
            addCriterion("r_main_thing in", values, "rMainThing");
            return (Criteria) this;
        }

        public Criteria andRMainThingNotIn(List<Byte> values) {
            addCriterion("r_main_thing not in", values, "rMainThing");
            return (Criteria) this;
        }

        public Criteria andRMainThingBetween(Byte value1, Byte value2) {
            addCriterion("r_main_thing between", value1, value2, "rMainThing");
            return (Criteria) this;
        }

        public Criteria andRMainThingNotBetween(Byte value1, Byte value2) {
            addCriterion("r_main_thing not between", value1, value2, "rMainThing");
            return (Criteria) this;
        }

        public Criteria andRResultIsNull() {
            addCriterion("r_result is null");
            return (Criteria) this;
        }

        public Criteria andRResultIsNotNull() {
            addCriterion("r_result is not null");
            return (Criteria) this;
        }

        public Criteria andRResultEqualTo(String value) {
            addCriterion("r_result =", value, "rResult");
            return (Criteria) this;
        }

        public Criteria andRResultNotEqualTo(String value) {
            addCriterion("r_result <>", value, "rResult");
            return (Criteria) this;
        }

        public Criteria andRResultGreaterThan(String value) {
            addCriterion("r_result >", value, "rResult");
            return (Criteria) this;
        }

        public Criteria andRResultGreaterThanOrEqualTo(String value) {
            addCriterion("r_result >=", value, "rResult");
            return (Criteria) this;
        }

        public Criteria andRResultLessThan(String value) {
            addCriterion("r_result <", value, "rResult");
            return (Criteria) this;
        }

        public Criteria andRResultLessThanOrEqualTo(String value) {
            addCriterion("r_result <=", value, "rResult");
            return (Criteria) this;
        }

        public Criteria andRResultLike(String value) {
            addCriterion("r_result like", value, "rResult");
            return (Criteria) this;
        }

        public Criteria andRResultNotLike(String value) {
            addCriterion("r_result not like", value, "rResult");
            return (Criteria) this;
        }

        public Criteria andRResultIn(List<String> values) {
            addCriterion("r_result in", values, "rResult");
            return (Criteria) this;
        }

        public Criteria andRResultNotIn(List<String> values) {
            addCriterion("r_result not in", values, "rResult");
            return (Criteria) this;
        }

        public Criteria andRResultBetween(String value1, String value2) {
            addCriterion("r_result between", value1, value2, "rResult");
            return (Criteria) this;
        }

        public Criteria andRResultNotBetween(String value1, String value2) {
            addCriterion("r_result not between", value1, value2, "rResult");
            return (Criteria) this;
        }

        public Criteria andRRemarkIsNull() {
            addCriterion("r_remark is null");
            return (Criteria) this;
        }

        public Criteria andRRemarkIsNotNull() {
            addCriterion("r_remark is not null");
            return (Criteria) this;
        }

        public Criteria andRRemarkEqualTo(String value) {
            addCriterion("r_remark =", value, "rRemark");
            return (Criteria) this;
        }

        public Criteria andRRemarkNotEqualTo(String value) {
            addCriterion("r_remark <>", value, "rRemark");
            return (Criteria) this;
        }

        public Criteria andRRemarkGreaterThan(String value) {
            addCriterion("r_remark >", value, "rRemark");
            return (Criteria) this;
        }

        public Criteria andRRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("r_remark >=", value, "rRemark");
            return (Criteria) this;
        }

        public Criteria andRRemarkLessThan(String value) {
            addCriterion("r_remark <", value, "rRemark");
            return (Criteria) this;
        }

        public Criteria andRRemarkLessThanOrEqualTo(String value) {
            addCriterion("r_remark <=", value, "rRemark");
            return (Criteria) this;
        }

        public Criteria andRRemarkLike(String value) {
            addCriterion("r_remark like", value, "rRemark");
            return (Criteria) this;
        }

        public Criteria andRRemarkNotLike(String value) {
            addCriterion("r_remark not like", value, "rRemark");
            return (Criteria) this;
        }

        public Criteria andRRemarkIn(List<String> values) {
            addCriterion("r_remark in", values, "rRemark");
            return (Criteria) this;
        }

        public Criteria andRRemarkNotIn(List<String> values) {
            addCriterion("r_remark not in", values, "rRemark");
            return (Criteria) this;
        }

        public Criteria andRRemarkBetween(String value1, String value2) {
            addCriterion("r_remark between", value1, value2, "rRemark");
            return (Criteria) this;
        }

        public Criteria andRRemarkNotBetween(String value1, String value2) {
            addCriterion("r_remark not between", value1, value2, "rRemark");
            return (Criteria) this;
        }

        public Criteria andRPicpathIsNull() {
            addCriterion("r_picpath is null");
            return (Criteria) this;
        }

        public Criteria andRPicpathIsNotNull() {
            addCriterion("r_picpath is not null");
            return (Criteria) this;
        }

        public Criteria andRPicpathEqualTo(String value) {
            addCriterion("r_picpath =", value, "rPicpath");
            return (Criteria) this;
        }

        public Criteria andRPicpathNotEqualTo(String value) {
            addCriterion("r_picpath <>", value, "rPicpath");
            return (Criteria) this;
        }

        public Criteria andRPicpathGreaterThan(String value) {
            addCriterion("r_picpath >", value, "rPicpath");
            return (Criteria) this;
        }

        public Criteria andRPicpathGreaterThanOrEqualTo(String value) {
            addCriterion("r_picpath >=", value, "rPicpath");
            return (Criteria) this;
        }

        public Criteria andRPicpathLessThan(String value) {
            addCriterion("r_picpath <", value, "rPicpath");
            return (Criteria) this;
        }

        public Criteria andRPicpathLessThanOrEqualTo(String value) {
            addCriterion("r_picpath <=", value, "rPicpath");
            return (Criteria) this;
        }

        public Criteria andRPicpathLike(String value) {
            addCriterion("r_picpath like", value, "rPicpath");
            return (Criteria) this;
        }

        public Criteria andRPicpathNotLike(String value) {
            addCriterion("r_picpath not like", value, "rPicpath");
            return (Criteria) this;
        }

        public Criteria andRPicpathIn(List<String> values) {
            addCriterion("r_picpath in", values, "rPicpath");
            return (Criteria) this;
        }

        public Criteria andRPicpathNotIn(List<String> values) {
            addCriterion("r_picpath not in", values, "rPicpath");
            return (Criteria) this;
        }

        public Criteria andRPicpathBetween(String value1, String value2) {
            addCriterion("r_picpath between", value1, value2, "rPicpath");
            return (Criteria) this;
        }

        public Criteria andRPicpathNotBetween(String value1, String value2) {
            addCriterion("r_picpath not between", value1, value2, "rPicpath");
            return (Criteria) this;
        }

        public Criteria andRNameIsNull() {
            addCriterion("r_name is null");
            return (Criteria) this;
        }

        public Criteria andRNameIsNotNull() {
            addCriterion("r_name is not null");
            return (Criteria) this;
        }

        public Criteria andRNameEqualTo(String value) {
            addCriterion("r_name =", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotEqualTo(String value) {
            addCriterion("r_name <>", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameGreaterThan(String value) {
            addCriterion("r_name >", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameGreaterThanOrEqualTo(String value) {
            addCriterion("r_name >=", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLessThan(String value) {
            addCriterion("r_name <", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLessThanOrEqualTo(String value) {
            addCriterion("r_name <=", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLike(String value) {
            addCriterion("r_name like", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotLike(String value) {
            addCriterion("r_name not like", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameIn(List<String> values) {
            addCriterion("r_name in", values, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotIn(List<String> values) {
            addCriterion("r_name not in", values, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameBetween(String value1, String value2) {
            addCriterion("r_name between", value1, value2, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotBetween(String value1, String value2) {
            addCriterion("r_name not between", value1, value2, "rName");
            return (Criteria) this;
        }

        public Criteria andDelStatusIsNull() {
            addCriterion("del_status is null");
            return (Criteria) this;
        }

        public Criteria andDelStatusIsNotNull() {
            addCriterion("del_status is not null");
            return (Criteria) this;
        }

        public Criteria andDelStatusEqualTo(Byte value) {
            addCriterion("del_status =", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusNotEqualTo(Byte value) {
            addCriterion("del_status <>", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusGreaterThan(Byte value) {
            addCriterion("del_status >", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("del_status >=", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusLessThan(Byte value) {
            addCriterion("del_status <", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusLessThanOrEqualTo(Byte value) {
            addCriterion("del_status <=", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusIn(List<Byte> values) {
            addCriterion("del_status in", values, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusNotIn(List<Byte> values) {
            addCriterion("del_status not in", values, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusBetween(Byte value1, Byte value2) {
            addCriterion("del_status between", value1, value2, "delStatus");
            return (Criteria) this;
        }

        public Criteria andDelStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("del_status not between", value1, value2, "delStatus");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNull() {
            addCriterion("create_name is null");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNotNull() {
            addCriterion("create_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreateNameEqualTo(String value) {
            addCriterion("create_name =", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("create_name <>", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThan(String value) {
            addCriterion("create_name >", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_name >=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThan(String value) {
            addCriterion("create_name <", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("create_name <=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLike(String value) {
            addCriterion("create_name like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotLike(String value) {
            addCriterion("create_name not like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameIn(List<String> values) {
            addCriterion("create_name in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotIn(List<String> values) {
            addCriterion("create_name not in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("create_name between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("create_name not between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNull() {
            addCriterion("update_name is null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNotNull() {
            addCriterion("update_name is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameEqualTo(String value) {
            addCriterion("update_name =", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotEqualTo(String value) {
            addCriterion("update_name <>", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThan(String value) {
            addCriterion("update_name >", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
            addCriterion("update_name >=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThan(String value) {
            addCriterion("update_name <", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThanOrEqualTo(String value) {
            addCriterion("update_name <=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLike(String value) {
            addCriterion("update_name like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotLike(String value) {
            addCriterion("update_name not like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIn(List<String> values) {
            addCriterion("update_name in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotIn(List<String> values) {
            addCriterion("update_name not in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameBetween(String value1, String value2) {
            addCriterion("update_name between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotBetween(String value1, String value2) {
            addCriterion("update_name not between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oa_record
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}