package com.sy.modules.entity.oa;

import java.io.Serializable;
import java.util.Date;

public class OaRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_record.r_id
     *
     * @mbggenerated
     */
    private Long rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_record.c_id
     *
     * @mbggenerated
     */
    private Long cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_record.r_customer
     *
     * @mbggenerated
     */
    private String rCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_record.r_mode
     *
     * @mbggenerated
     */
    private Byte rMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_record.r_main_thing
     *
     * @mbggenerated
     */
    private Byte rMainThing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_record.r_result
     *
     * @mbggenerated
     */
    private String rResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_record.r_remark
     *
     * @mbggenerated
     */
    private String rRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_record.r_picpath
     *
     * @mbggenerated
     */
    private String rPicpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_record.r_name
     *
     * @mbggenerated
     */
    private String rName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_record.del_status
     *
     * @mbggenerated
     */
    private Byte delStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_record.create_name
     *
     * @mbggenerated
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_record.update_name
     *
     * @mbggenerated
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_record.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_record.r_id
     *
     * @return the value of oa_record.r_id
     *
     * @mbggenerated
     */
    public Long getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_record.r_id
     *
     * @param rId the value for oa_record.r_id
     *
     * @mbggenerated
     */
    public void setrId(Long rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_record.c_id
     *
     * @return the value of oa_record.c_id
     *
     * @mbggenerated
     */
    public Long getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_record.c_id
     *
     * @param cId the value for oa_record.c_id
     *
     * @mbggenerated
     */
    public void setcId(Long cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_record.r_customer
     *
     * @return the value of oa_record.r_customer
     *
     * @mbggenerated
     */
    public String getrCustomer() {
        return rCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_record.r_customer
     *
     * @param rCustomer the value for oa_record.r_customer
     *
     * @mbggenerated
     */
    public void setrCustomer(String rCustomer) {
        this.rCustomer = rCustomer == null ? null : rCustomer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_record.r_mode
     *
     * @return the value of oa_record.r_mode
     *
     * @mbggenerated
     */
    public Byte getrMode() {
        return rMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_record.r_mode
     *
     * @param rMode the value for oa_record.r_mode
     *
     * @mbggenerated
     */
    public void setrMode(Byte rMode) {
        this.rMode = rMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_record.r_main_thing
     *
     * @return the value of oa_record.r_main_thing
     *
     * @mbggenerated
     */
    public Byte getrMainThing() {
        return rMainThing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_record.r_main_thing
     *
     * @param rMainThing the value for oa_record.r_main_thing
     *
     * @mbggenerated
     */
    public void setrMainThing(Byte rMainThing) {
        this.rMainThing = rMainThing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_record.r_result
     *
     * @return the value of oa_record.r_result
     *
     * @mbggenerated
     */
    public String getrResult() {
        return rResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_record.r_result
     *
     * @param rResult the value for oa_record.r_result
     *
     * @mbggenerated
     */
    public void setrResult(String rResult) {
        this.rResult = rResult == null ? null : rResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_record.r_remark
     *
     * @return the value of oa_record.r_remark
     *
     * @mbggenerated
     */
    public String getrRemark() {
        return rRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_record.r_remark
     *
     * @param rRemark the value for oa_record.r_remark
     *
     * @mbggenerated
     */
    public void setrRemark(String rRemark) {
        this.rRemark = rRemark == null ? null : rRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_record.r_picpath
     *
     * @return the value of oa_record.r_picpath
     *
     * @mbggenerated
     */
    public String getrPicpath() {
        return rPicpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_record.r_picpath
     *
     * @param rPicpath the value for oa_record.r_picpath
     *
     * @mbggenerated
     */
    public void setrPicpath(String rPicpath) {
        this.rPicpath = rPicpath == null ? null : rPicpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_record.r_name
     *
     * @return the value of oa_record.r_name
     *
     * @mbggenerated
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_record.r_name
     *
     * @param rName the value for oa_record.r_name
     *
     * @mbggenerated
     */
    public void setrName(String rName) {
        this.rName = rName == null ? null : rName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_record.del_status
     *
     * @return the value of oa_record.del_status
     *
     * @mbggenerated
     */
    public Byte getDelStatus() {
        return delStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_record.del_status
     *
     * @param delStatus the value for oa_record.del_status
     *
     * @mbggenerated
     */
    public void setDelStatus(Byte delStatus) {
        this.delStatus = delStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_record.create_name
     *
     * @return the value of oa_record.create_name
     *
     * @mbggenerated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_record.create_name
     *
     * @param createName the value for oa_record.create_name
     *
     * @mbggenerated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_record.create_time
     *
     * @return the value of oa_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_record.create_time
     *
     * @param createTime the value for oa_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_record.update_name
     *
     * @return the value of oa_record.update_name
     *
     * @mbggenerated
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_record.update_name
     *
     * @param updateName the value for oa_record.update_name
     *
     * @mbggenerated
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_record.update_time
     *
     * @return the value of oa_record.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_record.update_time
     *
     * @param updateTime the value for oa_record.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}