package com.sy.modules.entity.sys;

import java.io.Serializable;
import java.util.Date;

public class SysEmployee implements Serializable {
	
	private Integer delStatus;
	private SysUser sysuser;
	
	
    public SysUser getSysuser() {
		return sysuser;
	}

	public void setSysuser(SysUser sysuser) {
		this.sysuser = sysuser;
	}

	public Integer getDelStatus() {
		return delStatus;
	}

	public void setDelStatus(Integer delStatus) {
		this.delStatus = delStatus;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.e_id
     *
     * @mbggenerated
     */
    private Integer eId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.sys_user_id
     *
     * @mbggenerated
     */
    private Integer sysUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.e_number
     *
     * @mbggenerated
     */
    private String eNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.e_name
     *
     * @mbggenerated
     */
    private String eName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.e_en_name
     *
     * @mbggenerated
     */
    private String eEnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.e_phone
     *
     * @mbggenerated
     */
    private String ePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.e_mobile
     *
     * @mbggenerated
     */
    private String eMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.e_sex
     *
     * @mbggenerated
     */
    private Integer eSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.e_birthday
     *
     * @mbggenerated
     */
    private String eBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.e_mail
     *
     * @mbggenerated
     */
    private String eMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.e_address
     *
     * @mbggenerated
     */
    private String eAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.e_college
     *
     * @mbggenerated
     */
    private String eCollege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.e_education
     *
     * @mbggenerated
     */
    private Integer eEducation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.e_state
     *
     * @mbggenerated
     */
    private Integer eState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.create_name
     *
     * @mbggenerated
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.update_name
     *
     * @mbggenerated
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.e_id
     *
     * @return the value of sys_employee.e_id
     *
     * @mbggenerated
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.e_id
     *
     * @param eId the value for sys_employee.e_id
     *
     * @mbggenerated
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.sys_user_id
     *
     * @return the value of sys_employee.sys_user_id
     *
     * @mbggenerated
     */
    public Integer getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.sys_user_id
     *
     * @param sysUserId the value for sys_employee.sys_user_id
     *
     * @mbggenerated
     */
    public void setSysUserId(Integer sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.e_number
     *
     * @return the value of sys_employee.e_number
     *
     * @mbggenerated
     */
    public String geteNumber() {
        return eNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.e_number
     *
     * @param eNumber the value for sys_employee.e_number
     *
     * @mbggenerated
     */
    public void seteNumber(String eNumber) {
        this.eNumber = eNumber == null ? null : eNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.e_name
     *
     * @return the value of sys_employee.e_name
     *
     * @mbggenerated
     */
    public String geteName() {
        return eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.e_name
     *
     * @param eName the value for sys_employee.e_name
     *
     * @mbggenerated
     */
    public void seteName(String eName) {
        this.eName = eName == null ? null : eName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.e_en_name
     *
     * @return the value of sys_employee.e_en_name
     *
     * @mbggenerated
     */
    public String geteEnName() {
        return eEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.e_en_name
     *
     * @param eEnName the value for sys_employee.e_en_name
     *
     * @mbggenerated
     */
    public void seteEnName(String eEnName) {
        this.eEnName = eEnName == null ? null : eEnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.e_phone
     *
     * @return the value of sys_employee.e_phone
     *
     * @mbggenerated
     */
    public String getePhone() {
        return ePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.e_phone
     *
     * @param ePhone the value for sys_employee.e_phone
     *
     * @mbggenerated
     */
    public void setePhone(String ePhone) {
        this.ePhone = ePhone == null ? null : ePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.e_mobile
     *
     * @return the value of sys_employee.e_mobile
     *
     * @mbggenerated
     */
    public String geteMobile() {
        return eMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.e_mobile
     *
     * @param eMobile the value for sys_employee.e_mobile
     *
     * @mbggenerated
     */
    public void seteMobile(String eMobile) {
        this.eMobile = eMobile == null ? null : eMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.e_sex
     *
     * @return the value of sys_employee.e_sex
     *
     * @mbggenerated
     */
    public Integer geteSex() {
        return eSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.e_sex
     *
     * @param eSex the value for sys_employee.e_sex
     *
     * @mbggenerated
     */
    public void seteSex(Integer eSex) {
        this.eSex = eSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.e_birthday
     *
     * @return the value of sys_employee.e_birthday
     *
     * @mbggenerated
     */
    public String geteBirthday() {
        return eBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.e_birthday
     *
     * @param eBirthday the value for sys_employee.e_birthday
     *
     * @mbggenerated
     */
    public void seteBirthday(String eBirthday) {
        this.eBirthday = eBirthday == null ? null : eBirthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.e_mail
     *
     * @return the value of sys_employee.e_mail
     *
     * @mbggenerated
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.e_mail
     *
     * @param eMail the value for sys_employee.e_mail
     *
     * @mbggenerated
     */
    public void seteMail(String eMail) {
        this.eMail = eMail == null ? null : eMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.e_address
     *
     * @return the value of sys_employee.e_address
     *
     * @mbggenerated
     */
    public String geteAddress() {
        return eAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.e_address
     *
     * @param eAddress the value for sys_employee.e_address
     *
     * @mbggenerated
     */
    public void seteAddress(String eAddress) {
        this.eAddress = eAddress == null ? null : eAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.e_college
     *
     * @return the value of sys_employee.e_college
     *
     * @mbggenerated
     */
    public String geteCollege() {
        return eCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.e_college
     *
     * @param eCollege the value for sys_employee.e_college
     *
     * @mbggenerated
     */
    public void seteCollege(String eCollege) {
        this.eCollege = eCollege == null ? null : eCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.e_education
     *
     * @return the value of sys_employee.e_education
     *
     * @mbggenerated
     */
    public Integer geteEducation() {
        return eEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.e_education
     *
     * @param eEducation the value for sys_employee.e_education
     *
     * @mbggenerated
     */
    public void seteEducation(Integer eEducation) {
        this.eEducation = eEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.e_state
     *
     * @return the value of sys_employee.e_state
     *
     * @mbggenerated
     */
    public Integer geteState() {
        return eState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.e_state
     *
     * @param eState the value for sys_employee.e_state
     *
     * @mbggenerated
     */
    public void seteState(Integer eState) {
        this.eState = eState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.create_time
     *
     * @return the value of sys_employee.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.create_time
     *
     * @param createTime the value for sys_employee.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.create_name
     *
     * @return the value of sys_employee.create_name
     *
     * @mbggenerated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.create_name
     *
     * @param createName the value for sys_employee.create_name
     *
     * @mbggenerated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.update_time
     *
     * @return the value of sys_employee.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.update_time
     *
     * @param updateTime the value for sys_employee.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.update_name
     *
     * @return the value of sys_employee.update_name
     *
     * @mbggenerated
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.update_name
     *
     * @param updateName the value for sys_employee.update_name
     *
     * @mbggenerated
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }
}