package com.sy.modules.entity.sys;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysEmployeeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    public SysEmployeeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEIdIsNull() {
            addCriterion("e_id is null");
            return (Criteria) this;
        }

        public Criteria andEIdIsNotNull() {
            addCriterion("e_id is not null");
            return (Criteria) this;
        }

        public Criteria andEIdEqualTo(Integer value) {
            addCriterion("e_id =", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdNotEqualTo(Integer value) {
            addCriterion("e_id <>", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdGreaterThan(Integer value) {
            addCriterion("e_id >", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("e_id >=", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdLessThan(Integer value) {
            addCriterion("e_id <", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdLessThanOrEqualTo(Integer value) {
            addCriterion("e_id <=", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdIn(List<Integer> values) {
            addCriterion("e_id in", values, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdNotIn(List<Integer> values) {
            addCriterion("e_id not in", values, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdBetween(Integer value1, Integer value2) {
            addCriterion("e_id between", value1, value2, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdNotBetween(Integer value1, Integer value2) {
            addCriterion("e_id not between", value1, value2, "eId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdIsNull() {
            addCriterion("sys_user_id is null");
            return (Criteria) this;
        }

        public Criteria andSysUserIdIsNotNull() {
            addCriterion("sys_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andSysUserIdEqualTo(Integer value) {
            addCriterion("sys_user_id =", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotEqualTo(Integer value) {
            addCriterion("sys_user_id <>", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdGreaterThan(Integer value) {
            addCriterion("sys_user_id >", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sys_user_id >=", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdLessThan(Integer value) {
            addCriterion("sys_user_id <", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("sys_user_id <=", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdIn(List<Integer> values) {
            addCriterion("sys_user_id in", values, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotIn(List<Integer> values) {
            addCriterion("sys_user_id not in", values, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdBetween(Integer value1, Integer value2) {
            addCriterion("sys_user_id between", value1, value2, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sys_user_id not between", value1, value2, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andENumberIsNull() {
            addCriterion("e_number is null");
            return (Criteria) this;
        }

        public Criteria andENumberIsNotNull() {
            addCriterion("e_number is not null");
            return (Criteria) this;
        }

        public Criteria andENumberEqualTo(String value) {
            addCriterion("e_number =", value, "eNumber");
            return (Criteria) this;
        }

        public Criteria andENumberNotEqualTo(String value) {
            addCriterion("e_number <>", value, "eNumber");
            return (Criteria) this;
        }

        public Criteria andENumberGreaterThan(String value) {
            addCriterion("e_number >", value, "eNumber");
            return (Criteria) this;
        }

        public Criteria andENumberGreaterThanOrEqualTo(String value) {
            addCriterion("e_number >=", value, "eNumber");
            return (Criteria) this;
        }

        public Criteria andENumberLessThan(String value) {
            addCriterion("e_number <", value, "eNumber");
            return (Criteria) this;
        }

        public Criteria andENumberLessThanOrEqualTo(String value) {
            addCriterion("e_number <=", value, "eNumber");
            return (Criteria) this;
        }

        public Criteria andENumberLike(String value) {
            addCriterion("e_number like", value, "eNumber");
            return (Criteria) this;
        }

        public Criteria andENumberNotLike(String value) {
            addCriterion("e_number not like", value, "eNumber");
            return (Criteria) this;
        }

        public Criteria andENumberIn(List<String> values) {
            addCriterion("e_number in", values, "eNumber");
            return (Criteria) this;
        }

        public Criteria andENumberNotIn(List<String> values) {
            addCriterion("e_number not in", values, "eNumber");
            return (Criteria) this;
        }

        public Criteria andENumberBetween(String value1, String value2) {
            addCriterion("e_number between", value1, value2, "eNumber");
            return (Criteria) this;
        }

        public Criteria andENumberNotBetween(String value1, String value2) {
            addCriterion("e_number not between", value1, value2, "eNumber");
            return (Criteria) this;
        }

        public Criteria andENameIsNull() {
            addCriterion("e_name is null");
            return (Criteria) this;
        }

        public Criteria andENameIsNotNull() {
            addCriterion("e_name is not null");
            return (Criteria) this;
        }

        public Criteria andENameEqualTo(String value) {
            addCriterion("e_name =", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameNotEqualTo(String value) {
            addCriterion("e_name <>", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameGreaterThan(String value) {
            addCriterion("e_name >", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameGreaterThanOrEqualTo(String value) {
            addCriterion("e_name >=", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameLessThan(String value) {
            addCriterion("e_name <", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameLessThanOrEqualTo(String value) {
            addCriterion("e_name <=", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameLike(String value) {
            addCriterion("e_name like", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameNotLike(String value) {
            addCriterion("e_name not like", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameIn(List<String> values) {
            addCriterion("e_name in", values, "eName");
            return (Criteria) this;
        }

        public Criteria andENameNotIn(List<String> values) {
            addCriterion("e_name not in", values, "eName");
            return (Criteria) this;
        }

        public Criteria andENameBetween(String value1, String value2) {
            addCriterion("e_name between", value1, value2, "eName");
            return (Criteria) this;
        }

        public Criteria andENameNotBetween(String value1, String value2) {
            addCriterion("e_name not between", value1, value2, "eName");
            return (Criteria) this;
        }

        public Criteria andEEnNameIsNull() {
            addCriterion("e_en_name is null");
            return (Criteria) this;
        }

        public Criteria andEEnNameIsNotNull() {
            addCriterion("e_en_name is not null");
            return (Criteria) this;
        }

        public Criteria andEEnNameEqualTo(String value) {
            addCriterion("e_en_name =", value, "eEnName");
            return (Criteria) this;
        }

        public Criteria andEEnNameNotEqualTo(String value) {
            addCriterion("e_en_name <>", value, "eEnName");
            return (Criteria) this;
        }

        public Criteria andEEnNameGreaterThan(String value) {
            addCriterion("e_en_name >", value, "eEnName");
            return (Criteria) this;
        }

        public Criteria andEEnNameGreaterThanOrEqualTo(String value) {
            addCriterion("e_en_name >=", value, "eEnName");
            return (Criteria) this;
        }

        public Criteria andEEnNameLessThan(String value) {
            addCriterion("e_en_name <", value, "eEnName");
            return (Criteria) this;
        }

        public Criteria andEEnNameLessThanOrEqualTo(String value) {
            addCriterion("e_en_name <=", value, "eEnName");
            return (Criteria) this;
        }

        public Criteria andEEnNameLike(String value) {
            addCriterion("e_en_name like", value, "eEnName");
            return (Criteria) this;
        }

        public Criteria andEEnNameNotLike(String value) {
            addCriterion("e_en_name not like", value, "eEnName");
            return (Criteria) this;
        }

        public Criteria andEEnNameIn(List<String> values) {
            addCriterion("e_en_name in", values, "eEnName");
            return (Criteria) this;
        }

        public Criteria andEEnNameNotIn(List<String> values) {
            addCriterion("e_en_name not in", values, "eEnName");
            return (Criteria) this;
        }

        public Criteria andEEnNameBetween(String value1, String value2) {
            addCriterion("e_en_name between", value1, value2, "eEnName");
            return (Criteria) this;
        }

        public Criteria andEEnNameNotBetween(String value1, String value2) {
            addCriterion("e_en_name not between", value1, value2, "eEnName");
            return (Criteria) this;
        }

        public Criteria andEPhoneIsNull() {
            addCriterion("e_phone is null");
            return (Criteria) this;
        }

        public Criteria andEPhoneIsNotNull() {
            addCriterion("e_phone is not null");
            return (Criteria) this;
        }

        public Criteria andEPhoneEqualTo(String value) {
            addCriterion("e_phone =", value, "ePhone");
            return (Criteria) this;
        }

        public Criteria andEPhoneNotEqualTo(String value) {
            addCriterion("e_phone <>", value, "ePhone");
            return (Criteria) this;
        }

        public Criteria andEPhoneGreaterThan(String value) {
            addCriterion("e_phone >", value, "ePhone");
            return (Criteria) this;
        }

        public Criteria andEPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("e_phone >=", value, "ePhone");
            return (Criteria) this;
        }

        public Criteria andEPhoneLessThan(String value) {
            addCriterion("e_phone <", value, "ePhone");
            return (Criteria) this;
        }

        public Criteria andEPhoneLessThanOrEqualTo(String value) {
            addCriterion("e_phone <=", value, "ePhone");
            return (Criteria) this;
        }

        public Criteria andEPhoneLike(String value) {
            addCriterion("e_phone like", value, "ePhone");
            return (Criteria) this;
        }

        public Criteria andEPhoneNotLike(String value) {
            addCriterion("e_phone not like", value, "ePhone");
            return (Criteria) this;
        }

        public Criteria andEPhoneIn(List<String> values) {
            addCriterion("e_phone in", values, "ePhone");
            return (Criteria) this;
        }

        public Criteria andEPhoneNotIn(List<String> values) {
            addCriterion("e_phone not in", values, "ePhone");
            return (Criteria) this;
        }

        public Criteria andEPhoneBetween(String value1, String value2) {
            addCriterion("e_phone between", value1, value2, "ePhone");
            return (Criteria) this;
        }

        public Criteria andEPhoneNotBetween(String value1, String value2) {
            addCriterion("e_phone not between", value1, value2, "ePhone");
            return (Criteria) this;
        }

        public Criteria andEMobileIsNull() {
            addCriterion("e_mobile is null");
            return (Criteria) this;
        }

        public Criteria andEMobileIsNotNull() {
            addCriterion("e_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andEMobileEqualTo(String value) {
            addCriterion("e_mobile =", value, "eMobile");
            return (Criteria) this;
        }

        public Criteria andEMobileNotEqualTo(String value) {
            addCriterion("e_mobile <>", value, "eMobile");
            return (Criteria) this;
        }

        public Criteria andEMobileGreaterThan(String value) {
            addCriterion("e_mobile >", value, "eMobile");
            return (Criteria) this;
        }

        public Criteria andEMobileGreaterThanOrEqualTo(String value) {
            addCriterion("e_mobile >=", value, "eMobile");
            return (Criteria) this;
        }

        public Criteria andEMobileLessThan(String value) {
            addCriterion("e_mobile <", value, "eMobile");
            return (Criteria) this;
        }

        public Criteria andEMobileLessThanOrEqualTo(String value) {
            addCriterion("e_mobile <=", value, "eMobile");
            return (Criteria) this;
        }

        public Criteria andEMobileLike(String value) {
            addCriterion("e_mobile like", value, "eMobile");
            return (Criteria) this;
        }

        public Criteria andEMobileNotLike(String value) {
            addCriterion("e_mobile not like", value, "eMobile");
            return (Criteria) this;
        }

        public Criteria andEMobileIn(List<String> values) {
            addCriterion("e_mobile in", values, "eMobile");
            return (Criteria) this;
        }

        public Criteria andEMobileNotIn(List<String> values) {
            addCriterion("e_mobile not in", values, "eMobile");
            return (Criteria) this;
        }

        public Criteria andEMobileBetween(String value1, String value2) {
            addCriterion("e_mobile between", value1, value2, "eMobile");
            return (Criteria) this;
        }

        public Criteria andEMobileNotBetween(String value1, String value2) {
            addCriterion("e_mobile not between", value1, value2, "eMobile");
            return (Criteria) this;
        }

        public Criteria andESexIsNull() {
            addCriterion("e_sex is null");
            return (Criteria) this;
        }

        public Criteria andESexIsNotNull() {
            addCriterion("e_sex is not null");
            return (Criteria) this;
        }

        public Criteria andESexEqualTo(Integer value) {
            addCriterion("e_sex =", value, "eSex");
            return (Criteria) this;
        }

        public Criteria andESexNotEqualTo(Integer value) {
            addCriterion("e_sex <>", value, "eSex");
            return (Criteria) this;
        }

        public Criteria andESexGreaterThan(Integer value) {
            addCriterion("e_sex >", value, "eSex");
            return (Criteria) this;
        }

        public Criteria andESexGreaterThanOrEqualTo(Integer value) {
            addCriterion("e_sex >=", value, "eSex");
            return (Criteria) this;
        }

        public Criteria andESexLessThan(Integer value) {
            addCriterion("e_sex <", value, "eSex");
            return (Criteria) this;
        }

        public Criteria andESexLessThanOrEqualTo(Integer value) {
            addCriterion("e_sex <=", value, "eSex");
            return (Criteria) this;
        }

        public Criteria andESexIn(List<Integer> values) {
            addCriterion("e_sex in", values, "eSex");
            return (Criteria) this;
        }

        public Criteria andESexNotIn(List<Integer> values) {
            addCriterion("e_sex not in", values, "eSex");
            return (Criteria) this;
        }

        public Criteria andESexBetween(Integer value1, Integer value2) {
            addCriterion("e_sex between", value1, value2, "eSex");
            return (Criteria) this;
        }

        public Criteria andESexNotBetween(Integer value1, Integer value2) {
            addCriterion("e_sex not between", value1, value2, "eSex");
            return (Criteria) this;
        }

        public Criteria andEBirthdayIsNull() {
            addCriterion("e_birthday is null");
            return (Criteria) this;
        }

        public Criteria andEBirthdayIsNotNull() {
            addCriterion("e_birthday is not null");
            return (Criteria) this;
        }

        public Criteria andEBirthdayEqualTo(String value) {
            addCriterion("e_birthday =", value, "eBirthday");
            return (Criteria) this;
        }

        public Criteria andEBirthdayNotEqualTo(String value) {
            addCriterion("e_birthday <>", value, "eBirthday");
            return (Criteria) this;
        }

        public Criteria andEBirthdayGreaterThan(String value) {
            addCriterion("e_birthday >", value, "eBirthday");
            return (Criteria) this;
        }

        public Criteria andEBirthdayGreaterThanOrEqualTo(String value) {
            addCriterion("e_birthday >=", value, "eBirthday");
            return (Criteria) this;
        }

        public Criteria andEBirthdayLessThan(String value) {
            addCriterion("e_birthday <", value, "eBirthday");
            return (Criteria) this;
        }

        public Criteria andEBirthdayLessThanOrEqualTo(String value) {
            addCriterion("e_birthday <=", value, "eBirthday");
            return (Criteria) this;
        }

        public Criteria andEBirthdayLike(String value) {
            addCriterion("e_birthday like", value, "eBirthday");
            return (Criteria) this;
        }

        public Criteria andEBirthdayNotLike(String value) {
            addCriterion("e_birthday not like", value, "eBirthday");
            return (Criteria) this;
        }

        public Criteria andEBirthdayIn(List<String> values) {
            addCriterion("e_birthday in", values, "eBirthday");
            return (Criteria) this;
        }

        public Criteria andEBirthdayNotIn(List<String> values) {
            addCriterion("e_birthday not in", values, "eBirthday");
            return (Criteria) this;
        }

        public Criteria andEBirthdayBetween(String value1, String value2) {
            addCriterion("e_birthday between", value1, value2, "eBirthday");
            return (Criteria) this;
        }

        public Criteria andEBirthdayNotBetween(String value1, String value2) {
            addCriterion("e_birthday not between", value1, value2, "eBirthday");
            return (Criteria) this;
        }

        public Criteria andEMailIsNull() {
            addCriterion("e_mail is null");
            return (Criteria) this;
        }

        public Criteria andEMailIsNotNull() {
            addCriterion("e_mail is not null");
            return (Criteria) this;
        }

        public Criteria andEMailEqualTo(String value) {
            addCriterion("e_mail =", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotEqualTo(String value) {
            addCriterion("e_mail <>", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailGreaterThan(String value) {
            addCriterion("e_mail >", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailGreaterThanOrEqualTo(String value) {
            addCriterion("e_mail >=", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailLessThan(String value) {
            addCriterion("e_mail <", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailLessThanOrEqualTo(String value) {
            addCriterion("e_mail <=", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailLike(String value) {
            addCriterion("e_mail like", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotLike(String value) {
            addCriterion("e_mail not like", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailIn(List<String> values) {
            addCriterion("e_mail in", values, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotIn(List<String> values) {
            addCriterion("e_mail not in", values, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailBetween(String value1, String value2) {
            addCriterion("e_mail between", value1, value2, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotBetween(String value1, String value2) {
            addCriterion("e_mail not between", value1, value2, "eMail");
            return (Criteria) this;
        }

        public Criteria andEAddressIsNull() {
            addCriterion("e_address is null");
            return (Criteria) this;
        }

        public Criteria andEAddressIsNotNull() {
            addCriterion("e_address is not null");
            return (Criteria) this;
        }

        public Criteria andEAddressEqualTo(String value) {
            addCriterion("e_address =", value, "eAddress");
            return (Criteria) this;
        }

        public Criteria andEAddressNotEqualTo(String value) {
            addCriterion("e_address <>", value, "eAddress");
            return (Criteria) this;
        }

        public Criteria andEAddressGreaterThan(String value) {
            addCriterion("e_address >", value, "eAddress");
            return (Criteria) this;
        }

        public Criteria andEAddressGreaterThanOrEqualTo(String value) {
            addCriterion("e_address >=", value, "eAddress");
            return (Criteria) this;
        }

        public Criteria andEAddressLessThan(String value) {
            addCriterion("e_address <", value, "eAddress");
            return (Criteria) this;
        }

        public Criteria andEAddressLessThanOrEqualTo(String value) {
            addCriterion("e_address <=", value, "eAddress");
            return (Criteria) this;
        }

        public Criteria andEAddressLike(String value) {
            addCriterion("e_address like", value, "eAddress");
            return (Criteria) this;
        }

        public Criteria andEAddressNotLike(String value) {
            addCriterion("e_address not like", value, "eAddress");
            return (Criteria) this;
        }

        public Criteria andEAddressIn(List<String> values) {
            addCriterion("e_address in", values, "eAddress");
            return (Criteria) this;
        }

        public Criteria andEAddressNotIn(List<String> values) {
            addCriterion("e_address not in", values, "eAddress");
            return (Criteria) this;
        }

        public Criteria andEAddressBetween(String value1, String value2) {
            addCriterion("e_address between", value1, value2, "eAddress");
            return (Criteria) this;
        }

        public Criteria andEAddressNotBetween(String value1, String value2) {
            addCriterion("e_address not between", value1, value2, "eAddress");
            return (Criteria) this;
        }

        public Criteria andECollegeIsNull() {
            addCriterion("e_college is null");
            return (Criteria) this;
        }

        public Criteria andECollegeIsNotNull() {
            addCriterion("e_college is not null");
            return (Criteria) this;
        }

        public Criteria andECollegeEqualTo(String value) {
            addCriterion("e_college =", value, "eCollege");
            return (Criteria) this;
        }

        public Criteria andECollegeNotEqualTo(String value) {
            addCriterion("e_college <>", value, "eCollege");
            return (Criteria) this;
        }

        public Criteria andECollegeGreaterThan(String value) {
            addCriterion("e_college >", value, "eCollege");
            return (Criteria) this;
        }

        public Criteria andECollegeGreaterThanOrEqualTo(String value) {
            addCriterion("e_college >=", value, "eCollege");
            return (Criteria) this;
        }

        public Criteria andECollegeLessThan(String value) {
            addCriterion("e_college <", value, "eCollege");
            return (Criteria) this;
        }

        public Criteria andECollegeLessThanOrEqualTo(String value) {
            addCriterion("e_college <=", value, "eCollege");
            return (Criteria) this;
        }

        public Criteria andECollegeLike(String value) {
            addCriterion("e_college like", value, "eCollege");
            return (Criteria) this;
        }

        public Criteria andECollegeNotLike(String value) {
            addCriterion("e_college not like", value, "eCollege");
            return (Criteria) this;
        }

        public Criteria andECollegeIn(List<String> values) {
            addCriterion("e_college in", values, "eCollege");
            return (Criteria) this;
        }

        public Criteria andECollegeNotIn(List<String> values) {
            addCriterion("e_college not in", values, "eCollege");
            return (Criteria) this;
        }

        public Criteria andECollegeBetween(String value1, String value2) {
            addCriterion("e_college between", value1, value2, "eCollege");
            return (Criteria) this;
        }

        public Criteria andECollegeNotBetween(String value1, String value2) {
            addCriterion("e_college not between", value1, value2, "eCollege");
            return (Criteria) this;
        }

        public Criteria andEEducationIsNull() {
            addCriterion("e_education is null");
            return (Criteria) this;
        }

        public Criteria andEEducationIsNotNull() {
            addCriterion("e_education is not null");
            return (Criteria) this;
        }

        public Criteria andEEducationEqualTo(Integer value) {
            addCriterion("e_education =", value, "eEducation");
            return (Criteria) this;
        }

        public Criteria andEEducationNotEqualTo(Integer value) {
            addCriterion("e_education <>", value, "eEducation");
            return (Criteria) this;
        }

        public Criteria andEEducationGreaterThan(Integer value) {
            addCriterion("e_education >", value, "eEducation");
            return (Criteria) this;
        }

        public Criteria andEEducationGreaterThanOrEqualTo(Integer value) {
            addCriterion("e_education >=", value, "eEducation");
            return (Criteria) this;
        }

        public Criteria andEEducationLessThan(Integer value) {
            addCriterion("e_education <", value, "eEducation");
            return (Criteria) this;
        }

        public Criteria andEEducationLessThanOrEqualTo(Integer value) {
            addCriterion("e_education <=", value, "eEducation");
            return (Criteria) this;
        }

        public Criteria andEEducationIn(List<Integer> values) {
            addCriterion("e_education in", values, "eEducation");
            return (Criteria) this;
        }

        public Criteria andEEducationNotIn(List<Integer> values) {
            addCriterion("e_education not in", values, "eEducation");
            return (Criteria) this;
        }

        public Criteria andEEducationBetween(Integer value1, Integer value2) {
            addCriterion("e_education between", value1, value2, "eEducation");
            return (Criteria) this;
        }

        public Criteria andEEducationNotBetween(Integer value1, Integer value2) {
            addCriterion("e_education not between", value1, value2, "eEducation");
            return (Criteria) this;
        }

        public Criteria andEStateIsNull() {
            addCriterion("e_state is null");
            return (Criteria) this;
        }

        public Criteria andEStateIsNotNull() {
            addCriterion("e_state is not null");
            return (Criteria) this;
        }

        public Criteria andEStateEqualTo(Integer value) {
            addCriterion("e_state =", value, "eState");
            return (Criteria) this;
        }
        public Criteria andDelStatusEqualTo(Integer value) {
            addCriterion("del_status =", value, "delStatus");
            return (Criteria) this;
        }

        public Criteria andEStateNotEqualTo(Integer value) {
            addCriterion("e_state <>", value, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateGreaterThan(Integer value) {
            addCriterion("e_state >", value, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("e_state >=", value, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateLessThan(Integer value) {
            addCriterion("e_state <", value, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateLessThanOrEqualTo(Integer value) {
            addCriterion("e_state <=", value, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateIn(List<Integer> values) {
            addCriterion("e_state in", values, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateNotIn(List<Integer> values) {
            addCriterion("e_state not in", values, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateBetween(Integer value1, Integer value2) {
            addCriterion("e_state between", value1, value2, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateNotBetween(Integer value1, Integer value2) {
            addCriterion("e_state not between", value1, value2, "eState");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNull() {
            addCriterion("create_name is null");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNotNull() {
            addCriterion("create_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreateNameEqualTo(String value) {
            addCriterion("create_name =", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("create_name <>", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThan(String value) {
            addCriterion("create_name >", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_name >=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThan(String value) {
            addCriterion("create_name <", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("create_name <=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLike(String value) {
            addCriterion("create_name like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotLike(String value) {
            addCriterion("create_name not like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameIn(List<String> values) {
            addCriterion("create_name in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotIn(List<String> values) {
            addCriterion("create_name not in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("create_name between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("create_name not between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNull() {
            addCriterion("update_name is null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNotNull() {
            addCriterion("update_name is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameEqualTo(String value) {
            addCriterion("update_name =", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotEqualTo(String value) {
            addCriterion("update_name <>", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThan(String value) {
            addCriterion("update_name >", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
            addCriterion("update_name >=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThan(String value) {
            addCriterion("update_name <", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThanOrEqualTo(String value) {
            addCriterion("update_name <=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLike(String value) {
            addCriterion("update_name like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotLike(String value) {
            addCriterion("update_name not like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIn(List<String> values) {
            addCriterion("update_name in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotIn(List<String> values) {
            addCriterion("update_name not in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameBetween(String value1, String value2) {
            addCriterion("update_name between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotBetween(String value1, String value2) {
            addCriterion("update_name not between", value1, value2, "updateName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_employee
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_employee
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}