package com.sy.modules.entity.sys;

import java.io.Serializable;

public class SysMenu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.sm_id
     *
     * @mbggenerated
     */
    private Integer smId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.sm_name
     *
     * @mbggenerated
     */
    private String smName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.sm_uri
     *
     * @mbggenerated
     */
    private String smUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.sm_fatherId
     *
     * @mbggenerated
     */
    private Integer smFatherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.sm_rel
     *
     * @mbggenerated
     */
    private String smRel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.sm_state
     *
     * @mbggenerated
     */
    private Byte smState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.sm_id
     *
     * @return the value of sys_menu.sm_id
     *
     * @mbggenerated
     */
    public Integer getSmId() {
        return smId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.sm_id
     *
     * @param smId the value for sys_menu.sm_id
     *
     * @mbggenerated
     */
    public void setSmId(Integer smId) {
        this.smId = smId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.sm_name
     *
     * @return the value of sys_menu.sm_name
     *
     * @mbggenerated
     */
    public String getSmName() {
        return smName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.sm_name
     *
     * @param smName the value for sys_menu.sm_name
     *
     * @mbggenerated
     */
    public void setSmName(String smName) {
        this.smName = smName == null ? null : smName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.sm_uri
     *
     * @return the value of sys_menu.sm_uri
     *
     * @mbggenerated
     */
    public String getSmUri() {
        return smUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.sm_uri
     *
     * @param smUri the value for sys_menu.sm_uri
     *
     * @mbggenerated
     */
    public void setSmUri(String smUri) {
        this.smUri = smUri == null ? null : smUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.sm_fatherId
     *
     * @return the value of sys_menu.sm_fatherId
     *
     * @mbggenerated
     */
    public Integer getSmFatherid() {
        return smFatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.sm_fatherId
     *
     * @param smFatherid the value for sys_menu.sm_fatherId
     *
     * @mbggenerated
     */
    public void setSmFatherid(Integer smFatherid) {
        this.smFatherid = smFatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.sm_rel
     *
     * @return the value of sys_menu.sm_rel
     *
     * @mbggenerated
     */
    public String getSmRel() {
        return smRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.sm_rel
     *
     * @param smRel the value for sys_menu.sm_rel
     *
     * @mbggenerated
     */
    public void setSmRel(String smRel) {
        this.smRel = smRel == null ? null : smRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.sm_state
     *
     * @return the value of sys_menu.sm_state
     *
     * @mbggenerated
     */
    public Byte getSmState() {
        return smState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.sm_state
     *
     * @param smState the value for sys_menu.sm_state
     *
     * @mbggenerated
     */
    public void setSmState(Byte smState) {
        this.smState = smState;
    }
}