package com.sy.modules.entity.sys;

import java.util.ArrayList;
import java.util.List;

public class SysMenuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    public SysMenuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSmIdIsNull() {
            addCriterion("sm_id is null");
            return (Criteria) this;
        }

        public Criteria andSmIdIsNotNull() {
            addCriterion("sm_id is not null");
            return (Criteria) this;
        }

        public Criteria andSmIdEqualTo(Integer value) {
            addCriterion("sm_id =", value, "smId");
            return (Criteria) this;
        }

        public Criteria andSmIdNotEqualTo(Integer value) {
            addCriterion("sm_id <>", value, "smId");
            return (Criteria) this;
        }

        public Criteria andSmIdGreaterThan(Integer value) {
            addCriterion("sm_id >", value, "smId");
            return (Criteria) this;
        }

        public Criteria andSmIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sm_id >=", value, "smId");
            return (Criteria) this;
        }

        public Criteria andSmIdLessThan(Integer value) {
            addCriterion("sm_id <", value, "smId");
            return (Criteria) this;
        }

        public Criteria andSmIdLessThanOrEqualTo(Integer value) {
            addCriterion("sm_id <=", value, "smId");
            return (Criteria) this;
        }

        public Criteria andSmIdIn(List<Integer> values) {
            addCriterion("sm_id in", values, "smId");
            return (Criteria) this;
        }

        public Criteria andSmIdNotIn(List<Integer> values) {
            addCriterion("sm_id not in", values, "smId");
            return (Criteria) this;
        }

        public Criteria andSmIdBetween(Integer value1, Integer value2) {
            addCriterion("sm_id between", value1, value2, "smId");
            return (Criteria) this;
        }

        public Criteria andSmIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sm_id not between", value1, value2, "smId");
            return (Criteria) this;
        }

        public Criteria andSmNameIsNull() {
            addCriterion("sm_name is null");
            return (Criteria) this;
        }

        public Criteria andSmNameIsNotNull() {
            addCriterion("sm_name is not null");
            return (Criteria) this;
        }

        public Criteria andSmNameEqualTo(String value) {
            addCriterion("sm_name =", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameNotEqualTo(String value) {
            addCriterion("sm_name <>", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameGreaterThan(String value) {
            addCriterion("sm_name >", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameGreaterThanOrEqualTo(String value) {
            addCriterion("sm_name >=", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameLessThan(String value) {
            addCriterion("sm_name <", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameLessThanOrEqualTo(String value) {
            addCriterion("sm_name <=", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameLike(String value) {
            addCriterion("sm_name like", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameNotLike(String value) {
            addCriterion("sm_name not like", value, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameIn(List<String> values) {
            addCriterion("sm_name in", values, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameNotIn(List<String> values) {
            addCriterion("sm_name not in", values, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameBetween(String value1, String value2) {
            addCriterion("sm_name between", value1, value2, "smName");
            return (Criteria) this;
        }

        public Criteria andSmNameNotBetween(String value1, String value2) {
            addCriterion("sm_name not between", value1, value2, "smName");
            return (Criteria) this;
        }

        public Criteria andSmUriIsNull() {
            addCriterion("sm_uri is null");
            return (Criteria) this;
        }

        public Criteria andSmUriIsNotNull() {
            addCriterion("sm_uri is not null");
            return (Criteria) this;
        }

        public Criteria andSmUriEqualTo(String value) {
            addCriterion("sm_uri =", value, "smUri");
            return (Criteria) this;
        }

        public Criteria andSmUriNotEqualTo(String value) {
            addCriterion("sm_uri <>", value, "smUri");
            return (Criteria) this;
        }

        public Criteria andSmUriGreaterThan(String value) {
            addCriterion("sm_uri >", value, "smUri");
            return (Criteria) this;
        }

        public Criteria andSmUriGreaterThanOrEqualTo(String value) {
            addCriterion("sm_uri >=", value, "smUri");
            return (Criteria) this;
        }

        public Criteria andSmUriLessThan(String value) {
            addCriterion("sm_uri <", value, "smUri");
            return (Criteria) this;
        }

        public Criteria andSmUriLessThanOrEqualTo(String value) {
            addCriterion("sm_uri <=", value, "smUri");
            return (Criteria) this;
        }

        public Criteria andSmUriLike(String value) {
            addCriterion("sm_uri like", value, "smUri");
            return (Criteria) this;
        }

        public Criteria andSmUriNotLike(String value) {
            addCriterion("sm_uri not like", value, "smUri");
            return (Criteria) this;
        }

        public Criteria andSmUriIn(List<String> values) {
            addCriterion("sm_uri in", values, "smUri");
            return (Criteria) this;
        }

        public Criteria andSmUriNotIn(List<String> values) {
            addCriterion("sm_uri not in", values, "smUri");
            return (Criteria) this;
        }

        public Criteria andSmUriBetween(String value1, String value2) {
            addCriterion("sm_uri between", value1, value2, "smUri");
            return (Criteria) this;
        }

        public Criteria andSmUriNotBetween(String value1, String value2) {
            addCriterion("sm_uri not between", value1, value2, "smUri");
            return (Criteria) this;
        }

        public Criteria andSmFatheridIsNull() {
            addCriterion("sm_fatherId is null");
            return (Criteria) this;
        }

        public Criteria andSmFatheridIsNotNull() {
            addCriterion("sm_fatherId is not null");
            return (Criteria) this;
        }

        public Criteria andSmFatheridEqualTo(Integer value) {
            addCriterion("sm_fatherId =", value, "smFatherid");
            return (Criteria) this;
        }

        public Criteria andSmFatheridNotEqualTo(Integer value) {
            addCriterion("sm_fatherId <>", value, "smFatherid");
            return (Criteria) this;
        }

        public Criteria andSmFatheridGreaterThan(Integer value) {
            addCriterion("sm_fatherId >", value, "smFatherid");
            return (Criteria) this;
        }

        public Criteria andSmFatheridGreaterThanOrEqualTo(Integer value) {
            addCriterion("sm_fatherId >=", value, "smFatherid");
            return (Criteria) this;
        }

        public Criteria andSmFatheridLessThan(Integer value) {
            addCriterion("sm_fatherId <", value, "smFatherid");
            return (Criteria) this;
        }

        public Criteria andSmFatheridLessThanOrEqualTo(Integer value) {
            addCriterion("sm_fatherId <=", value, "smFatherid");
            return (Criteria) this;
        }

        public Criteria andSmFatheridIn(List<Integer> values) {
            addCriterion("sm_fatherId in", values, "smFatherid");
            return (Criteria) this;
        }

        public Criteria andSmFatheridNotIn(List<Integer> values) {
            addCriterion("sm_fatherId not in", values, "smFatherid");
            return (Criteria) this;
        }

        public Criteria andSmFatheridBetween(Integer value1, Integer value2) {
            addCriterion("sm_fatherId between", value1, value2, "smFatherid");
            return (Criteria) this;
        }

        public Criteria andSmFatheridNotBetween(Integer value1, Integer value2) {
            addCriterion("sm_fatherId not between", value1, value2, "smFatherid");
            return (Criteria) this;
        }

        public Criteria andSmRelIsNull() {
            addCriterion("sm_rel is null");
            return (Criteria) this;
        }

        public Criteria andSmRelIsNotNull() {
            addCriterion("sm_rel is not null");
            return (Criteria) this;
        }

        public Criteria andSmRelEqualTo(String value) {
            addCriterion("sm_rel =", value, "smRel");
            return (Criteria) this;
        }

        public Criteria andSmRelNotEqualTo(String value) {
            addCriterion("sm_rel <>", value, "smRel");
            return (Criteria) this;
        }

        public Criteria andSmRelGreaterThan(String value) {
            addCriterion("sm_rel >", value, "smRel");
            return (Criteria) this;
        }

        public Criteria andSmRelGreaterThanOrEqualTo(String value) {
            addCriterion("sm_rel >=", value, "smRel");
            return (Criteria) this;
        }

        public Criteria andSmRelLessThan(String value) {
            addCriterion("sm_rel <", value, "smRel");
            return (Criteria) this;
        }

        public Criteria andSmRelLessThanOrEqualTo(String value) {
            addCriterion("sm_rel <=", value, "smRel");
            return (Criteria) this;
        }

        public Criteria andSmRelLike(String value) {
            addCriterion("sm_rel like", value, "smRel");
            return (Criteria) this;
        }

        public Criteria andSmRelNotLike(String value) {
            addCriterion("sm_rel not like", value, "smRel");
            return (Criteria) this;
        }

        public Criteria andSmRelIn(List<String> values) {
            addCriterion("sm_rel in", values, "smRel");
            return (Criteria) this;
        }

        public Criteria andSmRelNotIn(List<String> values) {
            addCriterion("sm_rel not in", values, "smRel");
            return (Criteria) this;
        }

        public Criteria andSmRelBetween(String value1, String value2) {
            addCriterion("sm_rel between", value1, value2, "smRel");
            return (Criteria) this;
        }

        public Criteria andSmRelNotBetween(String value1, String value2) {
            addCriterion("sm_rel not between", value1, value2, "smRel");
            return (Criteria) this;
        }

        public Criteria andSmStateIsNull() {
            addCriterion("sm_state is null");
            return (Criteria) this;
        }

        public Criteria andSmStateIsNotNull() {
            addCriterion("sm_state is not null");
            return (Criteria) this;
        }

        public Criteria andSmStateEqualTo(Byte value) {
            addCriterion("sm_state =", value, "smState");
            return (Criteria) this;
        }

        public Criteria andSmStateNotEqualTo(Byte value) {
            addCriterion("sm_state <>", value, "smState");
            return (Criteria) this;
        }

        public Criteria andSmStateGreaterThan(Byte value) {
            addCriterion("sm_state >", value, "smState");
            return (Criteria) this;
        }

        public Criteria andSmStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("sm_state >=", value, "smState");
            return (Criteria) this;
        }

        public Criteria andSmStateLessThan(Byte value) {
            addCriterion("sm_state <", value, "smState");
            return (Criteria) this;
        }

        public Criteria andSmStateLessThanOrEqualTo(Byte value) {
            addCriterion("sm_state <=", value, "smState");
            return (Criteria) this;
        }

        public Criteria andSmStateIn(List<Byte> values) {
            addCriterion("sm_state in", values, "smState");
            return (Criteria) this;
        }

        public Criteria andSmStateNotIn(List<Byte> values) {
            addCriterion("sm_state not in", values, "smState");
            return (Criteria) this;
        }

        public Criteria andSmStateBetween(Byte value1, Byte value2) {
            addCriterion("sm_state between", value1, value2, "smState");
            return (Criteria) this;
        }

        public Criteria andSmStateNotBetween(Byte value1, Byte value2) {
            addCriterion("sm_state not between", value1, value2, "smState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_menu
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}