package com.sy.modules.entity.sys;

import java.io.Serializable;

public class WtRole implements Serializable {
	
	private Integer sysUserId; //所属公司id
	private Integer delState; //是否可用
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_role.wt_r_id
     *
     * @mbggenerated
     */
    private Integer wtRId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_role.wt_r_name
     *
     * @mbggenerated
     */
    private String wtRName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_role.wt_r_description
     *
     * @mbggenerated
     */
    private String wtRDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_role.wt_r_menuIds
     *
     * @mbggenerated
     */
    private String wtRMenuids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wt_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_role.wt_r_id
     *
     * @return the value of wt_role.wt_r_id
     *
     * @mbggenerated
     */
    public Integer getWtRId() {
        return wtRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_role.wt_r_id
     *
     * @param wtRId the value for wt_role.wt_r_id
     *
     * @mbggenerated
     */
    public void setWtRId(Integer wtRId) {
        this.wtRId = wtRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_role.wt_r_name
     *
     * @return the value of wt_role.wt_r_name
     *
     * @mbggenerated
     */
    public String getWtRName() {
        return wtRName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_role.wt_r_name
     *
     * @param wtRName the value for wt_role.wt_r_name
     *
     * @mbggenerated
     */
    public void setWtRName(String wtRName) {
        this.wtRName = wtRName == null ? null : wtRName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_role.wt_r_description
     *
     * @return the value of wt_role.wt_r_description
     *
     * @mbggenerated
     */
    public String getWtRDescription() {
        return wtRDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_role.wt_r_description
     *
     * @param wtRDescription the value for wt_role.wt_r_description
     *
     * @mbggenerated
     */
    public void setWtRDescription(String wtRDescription) {
        this.wtRDescription = wtRDescription == null ? null : wtRDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_role.wt_r_menuIds
     *
     * @return the value of wt_role.wt_r_menuIds
     *
     * @mbggenerated
     */
    public String getWtRMenuids() {
        return wtRMenuids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_role.wt_r_menuIds
     *
     * @param wtRMenuids the value for wt_role.wt_r_menuIds
     *
     * @mbggenerated
     */
    public void setWtRMenuids(String wtRMenuids) {
        this.wtRMenuids = wtRMenuids == null ? null : wtRMenuids.trim();
    }

	public Integer getSysUserId() {
		return sysUserId;
	}

	public void setSysUserId(Integer sysUserId) {
		this.sysUserId = sysUserId;
	}

	public Integer getDelState() {
		return delState;
	}

	public void setDelState(Integer delState) {
		this.delState = delState;
	}
}